---
podman_user: "{{ ansible_user }}"

# Proxy
bumper_proxy_enabled: false
bumper_proxy_http: ""
bumper_proxy_https: ""
bumper_proxy_no_proxy: ""
bumper_proxy_env: "{{ (['https_proxy=' ~ bumper_proxy_https] + (['http_proxy=' ~ bumper_proxy_http] if bumper_proxy_http else []) + (['no_proxy=' ~ bumper_proxy_no_proxy] if bumper_proxy_no_proxy else [])) if bumper_proxy_enabled else [] }}"

# Network
bumper_network_enabled: true
bumper_network_name: "bumper-internal"
bumper_network_driver: "bridge"
bumper_network_internal: false

# Build
bumper_version: "latest"
bumper_commit: "86bf91be27bf23bddc1e122013713d1c8f7ca53a"

# Autoupdate
bumper_autoupdate: true

# Environment
bumper_environment_vars:
  TZ: Europe/Berlin
  WEB_SERVER_HTTPS_PORT: 8443 # 443
  WEB_SERVER_LISTEN_PORT: 8007
  MQTT_LISTEN_PORT_TLS: 443 # 8883
  MQTT_LISTEN_PORT: 1883
  XMPP_LISTEN_PORT_TLS: 5223
  DEBUG_BUMPER_VERBOSE: 2
  DEBUG_BUMPER_LEVEL: "INFO"
