---
podman_user: "{{ ansible_user }}"

# Proxy
bumper_proxy_enabled: false
bumper_proxy_http: ""
bumper_proxy_https: ""
bumper_proxy_no_proxy: ""
bumper_proxy_env: "{{ (['https_proxy=' ~ bumper_proxy_https] + (['http_proxy=' ~ bumper_proxy_http] if bumper_proxy_http else []) + (['no_proxy=' ~ bumper_proxy_no_proxy] if bumper_proxy_no_proxy else [])) if bumper_proxy_enabled else [] }}"

# Network
bumper_network_enabled: true
bumper_network_name: "pasta"
bumper_network_driver: "bridge"
bumper_network_internal: false

# Envoy
bumper_envoy_enabled: true
bumper_envoy_version: "1.37"
bumper_envoy_external: true

# Service Discovery (future)
# bumper_discovery_enabled: false
# bumper_discovery_type: "etcd"
# bumper_discovery_etcd_host: ""
# bumper_discovery_etcd_port: 2379

# Build
bumper_version: "latest"
bumper_commit: "86bf91be27bf23bddc1e122013713d1c8f7ca53a"

# Autoupdate
bumper_autoupdate: true

# Environment
bumper_environment_vars:
  TZ: Europe/Berlin
  WEB_SERVER_HTTPS_PORT: 8443
  WEB_SERVER_LISTEN_PORT: "{{ '0.0.0.0:8007' if not bumper_envoy_enabled else '127.0.0.1:8007' }}"
  MQTT_LISTEN_PORT_TLS: 443
  MQTT_LISTEN_PORT: "{{ '0.0.0.0:1883' if not bumper_envoy_enabled else '127.0.0.1:1883' }}"
  XMPP_LISTEN_PORT_TLS: 5223
  DEBUG_BUMPER_VERBOSE: 2
  DEBUG_BUMPER_LEVEL: "INFO"
