---
podman_user: "container"

######################################
### giftpilz0.container.postgresql (provisioned by giftpilz0.container.forgejo)

postgresql_port_map_enabled: true
# normally use a separate administrator user; keep this legacy superuser here.
postgresql_admin_database: "forgejo"
postgresql_admin_user: "forgejo"
postgresql_admin_password: "{{ forgejo_db_password }}"
postgresql_databases:
  - name: "forgejo"
    user: "forgejo"
    password: "{{ forgejo_db_password }}"

# Versions
# renovate: datasource=docker depName=postgres
postgresql_version: "18.6-alpine"

# Autoupdate
postgresql_autoupdate: true
postgresql_backup_autoupdate: true

# Backup
postgresql_backup_schedule_times: "03:00"
postgresql_backup_retention_days: 7
postgresql_backup_compression: 6

###############################
### giftpilz0.container.forgejo

# Network
forgejo_network_enabled: true

# Network to join even when _network_enabled: false
forgejo_network_name: "forgejo-internal"

# Versions
# renovate: datasource=docker depName=codeberg.org/forgejo/forgejo
forgejo_version: "16.0.3"

# Autoupdate
forgejo_autoupdate: true

# Environment
forgejo_domain: "forgejo.nixpi.de"
forgejo_oauth_client_id: "forgejo"
forgejo_oauth_domain: "login.nixpi.de/realms/nixpi"
forgejo_oauth_name: "keycloak"
forgejo_oauth_admin_group: "forgejo-admin"

######################################
### giftpilz0.container.traefik

# Version
# renovate: datasource=docker depName=traefik
traefik_version: "v3.7.13"

# Rootless ports
traefik_unprivileged_port_start: 80

# Autoupdate
traefik_autoupdate: true

# ACME
traefik_acme_enabled: true
traefik_acme_ca_server: "https://acme-v02.api.letsencrypt.org/directory"
traefik_acme_challenge_type: dns
traefik_acme_dns_provider: "cloudflare"
traefik_acme_eab_enabled: false

# Logging
traefik_log_level: "INFO"

# Podman networks traefik should join to reach backends directly
traefik_networks:
  - forgejo

# HTTP services
traefik_http_services:
  - name: forgejo
    domain: forgejo.nixpi.de
    rule: "Host(`forgejo.nixpi.de`)"
    servers:
      - url: "http://forgejo-pod:3000"
    tls_enabled: true
    acme_enabled: true
