forgejo_db_password: ENC[AES256_GCM,data:Hio2UP0+qNo/a1PcoyAk+rMLlebQgmMKD8DhmcY9z7BqphTtOUqlzqrRCgP+h5e4,iv:HPu4KO1qnqX9MtlHERYP9pxcPVGGRl7jq8G00m12fec=,tag:YjPDi31HklJu6Cq0B2NSeQ==,type:str]
forgejo_oauth_client_secret: ENC[AES256_GCM,data:XIi6WjOqu3WVZvkqwj9cG24qk0frd8pBCbEF8jIWsrIoM34NQdTJjwhPSbApK+gm,iv:Njxa2U5ulsQ0010Sx8n1VcjzRcJsG/1Y2383NFLxaxM=,tag:1YCh/Xxsma15hx6O5sP9Kw==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:40/PeeLUK46uI9T14WxLlcrsy3MGj/pPyKA=,iv:EmYxk3j7VU8d29BhNGl3SGJOAr9NlQYv3fgXb6s/8vY=,tag:LRd9211JB2fpTJFU0luQrA==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:rVShSXWE76xSSRC7ju6iLyZqSuII0XnvQZmQjmx5SmlxCwRYchdN2Q==,iv:H1pSuylfIWRIoxnZbwSnRg7knsn6g0bHjI3FdtIh01c=,tag:8b3AjzVX2hP5pYmOm41C6A==,type:str]
sops:
    lastmodified: "2026-05-09T14:39:40Z"
    mac: ENC[AES256_GCM,data:tswxwOc14gOAPmeGEK48tmls3ecWrKoIG0B2KAbo4pSMoisSMpwCNsXLL1ZfS2ClS5FDc/yOudu4MmH2Y80iwlF6zEsH4QrsnLSe/gteN7a6+VdCsgEwfbN0ZEJv8Kdajtux9vOri3rXyHgJ05mezJo5BuU/fNo/Uj2YFVKFjqM=,iv:B3r1ZZD1sWLyn5sEIje48ZyVWS7ikvdXcAJZq7wp/6c=,tag:MvGEZjZB2XNlGzfWqAfu6A==,type:str]
    pgp:
        - created_at: "2026-05-09T14:39:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdACHxuQx+aKM0jbNGjlldUjq5RP/yPPBq9Ez6xIo6BB1Uw
            Lpk4Lco+/wA7BzH6G0d6VE9txWZ17QMZ58nzp/kV8wfsdh8oWWu9u2QF5S9nC7Ym
            0l4BT87aTn/7AKGIk1xmJBusQ5ExQdptQHOs00XDotiR1B8WzPCfzP1EqSdp1enN
            2eXftBNBdHX/he7fx5U8uU7gG8JgNaLFOCwY9E2jdwvAKusaf7KG0rbPJXV+7qFM
            =8DBd
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
