forgejo_db_password: ENC[AES256_GCM,data:MGikn9977XpC889SOY2IHLzCpMTApgk4VwmZGb1OauRau5BvG7GFGDAtNSHmx1NV,iv:xUDL0Q5Hi90fdf9g9SL0riXfsMld4ijLNibsaJMvnJs=,tag:U8U8yaYP5zy8zAXyoj5E2Q==,type:str]
forgejo_oauth_client_secret: ENC[AES256_GCM,data:Nn2sGjb6YXBYH7yQbWi7AIvIF8ZzgGOVquTUD1M38sKJVrenvC6ifVm/wfoCL8Gs,iv:S8rui6NuWtvgsQiV1SLc7LI4r64+WipRuUJzpjUfvh8=,tag:87hMsJGRWA8V7yq6IKjzYQ==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:OdSjg/Mw4qA+0QRgDfpKGPrG4BzwU7B1hA8=,iv:WdCJK5VSyaYDqq0KA9FWSEu9+2azSbCY2bOhyNu5Dd0=,tag:X9Jb6tuQons8KVg86zTEdw==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:CUuQlonPeyOAjF5gKpLQ7gu0Zz4mz5T8wuqQnwgT0Bmae/hXiKJA3Q==,iv:9C/zB+Y8ThQ7HeF22Iuey0Lr+R6UWIc3kyTre/odGys=,tag:6U1KeD3nh8OhvnfZfucqWA==,type:str]
sops:
    lastmodified: "2026-07-05T09:32:15Z"
    mac: ENC[AES256_GCM,data:ffZRAuto9L7gwyyQA0zgxXnG9cix0mq6gzkW0Dpko0GfDu2Y/jSUue1Z27yStNH8TPcKz6Vl3ukgzGiMT4PNgcYxHammPsgNCFM+PLiTOsOCxIHjU2vaFjs1UICtu5fo9ds+OTWXIcO2HuQON+tWK+RFEGEfAArLtSBBuw+wR0k=,iv:cONEUfHQd7JNPSnscIxKUgJ9YGfwv8MrOjieNg9WZK8=,tag:U8UUEZqE7sdVFT6UHe5fXQ==,type:str]
    pgp:
        - created_at: "2026-07-05T09:32:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAjXywxMqHG/u1bQFuMmjnNVIY2JJo7IsWln475wmhSFUw
            Zg7ffrEYBSsXUsfylGiWszIii3+JSt4bmHcQyPsA9nGv4F+VmFyiijvGKIBwoQYV
            0l4Br4EXh/VkvAFGko5EFLBbSJIKWLeYJ749wAKGltp9cHwyV2OMqtfVLDZpZ+he
            fC31xr3vZTVzYqhtBrSEE9AHt+YDZUG/TRPeogdCqZb2OKIG6vY4hJdivZwAqFH+
            =E8zf
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
