forgejo_db_password: ENC[AES256_GCM,data:F1Bdlf5iPOxttQ7v5DD9mItyx4aW1LAbf0Yk7CyBjJp+OtoNKtTmaqoeuWFEaX/v,iv:bvSU94F5PsxyTFLHJ459XlpgL5f1Yjq43DeaWSMAtzM=,tag:oV3XGJhCLgU4Qexf4dtDjQ==,type:str]
forgejo_oauth_client_secret: ENC[AES256_GCM,data:WFmtcZ+oX+S91UQ4SizA0BfvbAOsLw3SVqiG5GWQFIJl+zpCtu+Eenc3ILsJW3Hw,iv:Q0Y+mCzY2QZ9t5XjDQCh95h9Kyq3CXeFffArmth/fdw=,tag:P+AjDGEz6jHHHHNMr3J8zQ==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:84MNbUtXpCnB5lgIwriI1TxvNq6o7cL7vYU=,iv:sPJB++XYV5/JxTgz5yARFeZApuGGesSWJW2QNSG0h38=,tag:o2pZdO3OTP+CLF97vjidlA==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:enID7RRPah8L4e7vXSRci2DKwdMC7cXa7i7xpbbmNHskQmUopj2MSA==,iv:x+0UDr7/JzwPxSYzWo+lc1EHXU+b1PHg9LVhxA+hlY8=,tag:FGjdC4F4/KydSha7Q1UiZg==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:/3jZqSXp35pg61BF6jQjrsuljgWr3WdHOJYHSJUUcd97g1WD2zgmiW72Wb8WJSgTouIuNOb4ZmAKFlg4xB92pGP9S30eg6JoFljuDLcyg8vzGdixOSUk+bMmWJGhtvETVpA5qBAP5BN/xYZFSq/ciHCUiWQnYavOj2uOQBCY9OM=,iv:zU1ZO7uFT99SV1rYBwvZyh6sDYwqPFRqx2jBi9ouQjg=,tag:o9kcnpzPXRdopLZizdYEkw==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAYRzoqWugWCN+fw8lt1sj75j9EwhHaToJmFv9b2h26wgw
            U9o4KJOjxcIBHL5hJSdFaTKpeRNzk46JPVu0X/VZb/wyMhm18yR7h6zTFccKKml8
            0lwBiDTjUlQ9l5YjaR/lRTAvKg+ze3RnfopHliXMFIw6QuEN4Cys/OJl0pOEdkZm
            j0Yj44RYO0FNx3wsYlAVLGMjn7Tt0WzSDIXFADM7e8u1Gvq+9ioJXszMmc6/oQ==
            =pazJ
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
