---
podman_user: "{{ ansible_user }}"

# Proxy
homeassistant_proxy_enabled: false
homeassistant_proxy_http: ""
homeassistant_proxy_https: ""
homeassistant_proxy_no_proxy: ""
homeassistant_proxy_env: "{{ (['https_proxy=' ~ homeassistant_proxy_https] + (['http_proxy=' ~ homeassistant_proxy_http] if homeassistant_proxy_http else []) + (['no_proxy=' ~ homeassistant_proxy_no_proxy] if homeassistant_proxy_no_proxy else [])) if homeassistant_proxy_enabled else [] }}"

# Network
homeassistant_network_enabled: true
homeassistant_network_driver: "bridge"
homeassistant_network_internal: false

# Network to join even when _network_enabled: false
homeassistant_network_name: "homeassistant-internal"

# Envoy
homeassistant_envoy_enabled: true
homeassistant_envoy_version: "1.37-latest"

# Port mapping: host_port:container_port
homeassistant_port_map_enabled: true
homeassistant_port_map:
  - "8123:8123"

# Versions
homeassistant_version: "2026.2"

# Autoupdate
homeassistant_autoupdate: true

# Environment
homeassistant_environment_vars:
  TZ: Europe/Berlin

# Config
# homeassistant_device: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804114425-if00:/dev/ttyACM0"
# homeassistant_deebot_module: ""
