---
- name: "Profile: Install fastfetch"
  become: true
  ansible.builtin.package:
    name: fastfetch
    state: present

- name: "Profile: Create systemwide fastfetch config script"
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/fastfetch.sh
    content: |
      #!/bin/bash
      if command -v fastfetch >/dev/null 2>&1; then
        fastfetch
      fi
    mode: "0755"
    owner: root
    group: root

- name: "Profile: Get all user accounts from passwd"
  ansible.builtin.getent:
    database: passwd

- name: "Profile: Check if home directories exist"
  ansible.builtin.stat:
    path: "{{ item.value.4 }}"
  loop: "{{ getent_passwd | dict2items }}"
  register: home_dirs_stat
  when:
    - getent_passwd is defined
    - item.value.5 in ['/bin/bash', '/bin/sh', '/bin/zsh', '/usr/bin/bash', '/usr/bin/zsh']

- name: "Profile: Suppress default login messages for all users with valid shells"
  become: true
  ansible.builtin.file:
    path: "{{ item.item.value.4 }}/.hushlogin"
    state: touch
    owner: "{{ item.item.key }}"
    group: "{{ item.item.value.2 }}"
    mode: "0644"
    modification_time: preserve
    access_time: preserve
  loop: "{{ home_dirs_stat.results }}"
  when:
    - item is not skipped
    - item.stat.exists
    - item.stat.isdir
