---
- name: "MariaDB: Create Podman config directory"
  become: true
  ansible.builtin.file:
    path: /etc/containers/containers.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "MariaDB: Deploy podman proxy configuration"
  become: true
  ansible.builtin.template:
    src: "mariadb-pod/proxy.conf.j2"
    dest: "/etc/containers/containers.conf.d/proxy.conf"
    owner: root
    group: root
    mode: "0644"
  when: mariadb_proxy_enabled

- name: "MariaDB: Delete quadlet directory"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config/containers/systemd/mariadb-pod"
    state: absent

- name: "MariaDB: Enable lingering"
  become: true
  ansible.builtin.command: loginctl enable-linger {{ podman_user }}
  changed_when: true

- name: "MariaDB: Configure unprivileged port range for rootless containers"
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "80"
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-rootless-ports.conf
    reload: true

- name: "MariaDB: Create quadlet directory"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config/containers/systemd"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0755"

- name: "MariaDB: Create directory structure"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config/containers/systemd/{{ item.path }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "templates/"
  when: item.state == 'directory'

- name: "MariaDB: Create config directories"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config/containers/systemd/{{ item.path }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "files/"
  when: item.state == 'directory'

- name: "MariaDB: Copy config shell scripts"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/{{ podman_user }}/.config/containers/systemd/{{ item.path }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "files/"
  when: item.state == 'file'

- name: "MariaDB: Template quadlet files"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/home/{{ podman_user }}/.config/containers/systemd/{{ item.path }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "templates/"
  when: item.state == 'file'

- name: "MariaDB: Copy extra files"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/{{ podman_user }}/.config/containers/systemd/mariadb-pod/{{ item.dest }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: preserve
  loop: "{{ mariadb_extra_files | default([]) }}"
  when: "mariadb_extra_files | default([]) | length > 0"

- name: "MariaDB: Copy extra directories"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.copy:
    src: "{{ item.src }}/"
    dest: "/home/{{ podman_user }}/.config/containers/systemd/mariadb-pod/{{ item.dest }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: preserve
  loop: "{{ mariadb_extra_dirs | default([]) }}"
  when: "mariadb_extra_dirs | default([]) | length > 0"

- name: "MariaDB: systemd daemon reload"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: "MariaDB: Start network service"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: mariadb-network.service
    enabled: true
    state: restarted
    scope: user
  when: mariadb_network_enabled

- name: "MariaDB: Start pod service"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: mariadb-pod.service
    enabled: true
    state: restarted
    scope: user

- name: "MariaDB: Enable podman-auto-update timer"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    enabled: true
    state: started
    scope: user

- name: "MariaDB: Deploy CloudBeaver"
  ansible.builtin.include_role:
    name: giftpilz0.container.cloudbeaver
  vars:
    cloudbeaver_db_network_name: "{{ mariadb_network_name }}"
    cloudbeaver_db_type: "mariadb"
    cloudbeaver_db_host: "mariadb-pod"
    cloudbeaver_db_port: "3306"
    cloudbeaver_db_name: "{{ mariadb_db_name }}"
    cloudbeaver_db_user: "{{ mariadb_db_user }}"
    cloudbeaver_db_password: "{{ mariadb_db_password }}"
    cloudbeaver_admin_user: "{{ mariadb_cloudbeaver_admin_user }}"
    cloudbeaver_admin_password: "{{ mariadb_cloudbeaver_admin_password }}"
    cloudbeaver_proxy_enabled: "{{ mariadb_proxy_enabled }}"
    cloudbeaver_proxy_http: "{{ mariadb_proxy_http }}"
    cloudbeaver_proxy_https: "{{ mariadb_proxy_https }}"
    cloudbeaver_proxy_no_proxy: "{{ mariadb_proxy_no_proxy }}"
  when: mariadb_cloudbeaver_enabled

- name: "MariaDB: Configure traefik"
  ansible.builtin.include_role:
    name: giftpilz0.container.traefik
  when: traefik_http_services is defined or traefik_tcp_services is defined
