---
podman_user: "container"

######################################
### giftpilz0.container.vaultwarden

# Proxy
vaultwarden_proxy_enabled: false
vaultwarden_proxy_http: ""
vaultwarden_proxy_https: ""
vaultwarden_proxy_no_proxy: ""

# Network
vaultwarden_network_enabled: true
vaultwarden_network_driver: "bridge"
vaultwarden_network_internal: false

# Network to join even when _network_enabled: false
vaultwarden_network_name: "vaultwarden-internal"

# Versions
# renovate: datasource=docker depName=vaultwarden/server
vaultwarden_version: "1.36.0-alpine"

# Autoupdate
vaultwarden_autoupdate: true

# Environment
vaultwarden_domain: "https://vaultwarden.nixpi.de/"

vaultwarden_environment_vars:
  DOMAIN: "{{ vaultwarden_domain }}"
  ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
  ROCKET_PORT: "80"
  # SSO via Keycloak
  SSO_ENABLED: "true"
  SSO_AUTHORITY: "https://login.nixpi.de/realms/nixpi"
  SSO_CLIENT_ID: "vaultwarden"
  SSO_CLIENT_SECRET: "{{ vaultwarden_client_secret }}"

######################################
### giftpilz0.container.traefik

# Proxy
traefik_proxy_enabled: false
traefik_proxy_http: ""
traefik_proxy_https: ""
traefik_proxy_no_proxy: ""

# Version
# renovate: datasource=docker depName=traefik
traefik_version: "v3.7.5"

# Autoupdate
traefik_autoupdate: true

# ACME
traefik_acme_enabled: true
traefik_acme_ca_server: "https://acme-v02.api.letsencrypt.org/directory"
traefik_acme_challenge_type: dns
traefik_acme_dns_provider: "cloudflare"
traefik_acme_eab_enabled: false

# Logging
traefik_log_level: "INFO"

# Podman networks traefik should join to reach backends directly
traefik_networks:
  - vaultwarden

# HTTP services
traefik_http_services:
  - name: vaultwarden
    domain: vaultwarden.nixpi.de
    rule: "Host(`vaultwarden.nixpi.de`)"
    servers:
      - url: "http://vaultwarden-pod:80"
    tls_enabled: true
    acme_enabled: true
    health_check:
      path: "/alive"
      interval: "30s"
