vaultwarden_admin_token: ENC[AES256_GCM,data:azDtuezAoVJVrHoS7n8dZQvBf7RtGy7SmG5TGNcyoql+Xcnl9uNhVjtRY2XGvlb14priwBXM07dqbrfClvGYlCebvuHY6DtbvCjSBcerF3qtzHp9sT77nSvaAoFI3+gaDuA62NYVZvbGoIiDQQ9TyGNCry69XZ7RzTS8U2RvvS/xPJUvdrs=,iv:rIVeeBeHU8lnHQGkH0Mcwv5UU1TGlWVP1Oc9DZBF0HM=,tag:19N7lQPYm5kBUe6j/qL/uQ==,type:str]
vaultwarden_client_secret: ENC[AES256_GCM,data:1qmFs+2AZ0hPcWESZgFV2Shv0eigLvDxGlh5V7Yd30Qt3nxHhhiQdZwW7t8jI5g2,iv:YYmAhe0TKbAFI2JulR66LyvrAy5NssxCwX14DOu/uBI=,tag:VJ7nS56HvbPZ7VqBjg3Snw==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:mfG8eW0S9yNPqFp2pVRMDR8SkaAuCYOm1ZQ=,iv:SkeRaUMGZtUJFTuGKsbDnyq+UK8Xh8s0/GOrD54ujok=,tag:90b6Z4A8zRyYmtKd8ivn+Q==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:dMhCUu8QfhEg3Gc/Wpm1ROWVbUg0XxZYf1Vnttp52ZgiXIBp2nGCTA==,iv:P0cjaWqojtr5mSXXmMRmrXSRFn8G17lYMDQdZJRLQD8=,tag:p2LAnb+OS570hmRGpJsJlw==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:CByarzK9p6Zd1JAf0bsbpr+CvDTIGUco9Ilgb1Tw96PI8Te7svTd0db2xrJcOKjRjxJrLLTeHtcY+Tbnf3z9Y5+Exf/Lna6f3Rc2bLryO1UGJPC5pw7pBtNufilBVcAxrnTBVr/D+UxspWQiCHYJghlHC63Az/pVl2MVCmkDUcM=,iv:sw5TMY9tnRqoHTEWw716Rv35Am+oSLUUpFaMq8h1WXk=,tag:9Bi6W2fxVy6j/NBlp3y06w==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAHqbEaHj93L0kxGCK3tGTk/HtesUNalHNv5OmmEQewVQw
            4KL/Z86nKdg5Eegm03vzIlp6vycl+GQuHerlp+w5jvSawYw9Jwh8jSPrcqtVR1+k
            0l4BJLRDZj81QzjvdHDzfSdp1+76nym+NliFqeZdee7GMh1NvNJmPTY64b7ZMSgt
            Yfigb3clM8dPh2nZPTX5twBQtH/EyvFeaurGrdat3EKP/Cq2djDBfAydg+AKJW1x
            =vkcX
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
