vaultwarden_admin_token: ENC[AES256_GCM,data:ekovPTwkct75WdHmjoiPUUCjV31QDe8OtLv1jTOfWrsDdguahXptc51nzCPWWW9LFIW6dAcQxAPxqBMoaxqRqi/+VxhsCJmLwWfdDxm6LhqIg7yrlhSaNRSZB6FCUNiDoTYCPSHJctG7eQiWFTNcwVNXRo48Kd096GWHHsH4rex5Hgt2fmc=,iv:vW+9CSXL2BaS78LQU7LKgM0uiOsyjpzOUOTgqSmL198=,tag:dn0GvG6WXdwFoSHWNtfdtw==,type:str]
vaultwarden_client_secret: ENC[AES256_GCM,data:oPjgpCyCfBGDl+4UUnOKVkPyq5iR8iKO62DY4RfDH6X7IvNT5aWsBGTPP/kosjq1,iv:t7kh5LnmssvWaq9R6xwmJhUp4xB2J7WKkP0+kLKiKQM=,tag:9k2rwLEdMR3s8l2zdtEUAQ==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:5ME/69nrZ7pT9BDvyZFKurbqhC3pyICfMb4=,iv:mnl7UTZkyCMRXxpDZ02p7vcqDNPqCmV8TLR+4KwUm5c=,tag:H89x4+9lT6RqtoWJvYmb2A==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:JSMLt6oJZ03ynOmC8LukDwvdNgkUeg/KNuQxlNw5P1x7d9UCgCApXQ==,iv:FEvd/ivSy/PKpuXgnSWU5W8HIx9sGnBgVJ7FtEpzyPQ=,tag:nd5zbJJ4c0PO4n84ehhYeA==,type:str]
sops:
    lastmodified: "2026-05-09T14:39:40Z"
    mac: ENC[AES256_GCM,data:2puKw4cmGRyCTeB1UpjYURCsnGTTp74RNKW/UHToCZUVmHZt6h9NI8bpxL1EY3wKG4RvEfJtuDQl+ZrTzQdPWqtbwbmzg8U0cGwEr5lQXvPfDy6/gNiidgqRbYfJcjf0lIhlQLf2QJ7hQdBbzOJyBFOPh6QewUyEznub48TCn3A=,iv:io/YowT/yBqf0D0UgBB9fuC+hkbsdYauqQftLgA40T0=,tag:EnM6VBHvBWvZd2GgbAB1sg==,type:str]
    pgp:
        - created_at: "2026-05-09T14:39:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdARRvmLWbQh3A8FbGtV/YNsxx3HfFxY1KN167nB3A4WGQw
            QvJKGZV+PRcL1U4M0CB4QMipV7IfoIfBdoZHW0TLLu+AhL99KQng0B8xE2vaMdBj
            0lwB7SdUG9vYeLcTIEIK21T+ICvONbt2FLDEoU8bDrsweBtXsQTnZwfkhxljrmcW
            6Oc6zwsIfSPwGsAQ0keSORaPxrSTh3upNw4jA36FvKupaT9nZ/EuVMibP89GQw==
            =R+dV
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
