vaultwarden_admin_token: ENC[AES256_GCM,data:pnatJonuOnq7Lv/PzsmW6NsL9o7oMSIyEM+4TgMchzgVB2e+AJtSuyPNRoEuaCnlwP6pj4nXDQf1HmRddgc7KMl5A0za2mfrCPruMlC6GSgEQmOkVtZ1Yo8LhrZSUPiRigYxpvNWnANjMMFAr4Mv+taV2tWL4OnGOSuMa9tEkCXe9S5IH50=,iv:gQFnr9iiYBv6TgKrMtzorj+FJnB/1n+3SYEVSNLxMoY=,tag:Ofk5xUwrrDxCsfuztpwqlw==,type:str]
vaultwarden_client_secret: ENC[AES256_GCM,data:fIqCUgPEfGsQSgAvbtJdNRY+UKZ0Fy/GqALFeJaImJIvwbqoZccdWOE3LquTh1iX,iv:VtCjI5weXyWPkJqRVp+lNdD8BXXWmQN0hC0Mzw9yWZc=,tag:RRVtNqn+B31ww5Un8Igfhw==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:qFEnyEy/Ry3YROd298ED4xlqr82ol/tWLus=,iv:RqyJT3eq3y7M7ArXzqQuiHCvP+0PBbkk05sjc7qlKT8=,tag:4mM3sSvd2sIS+UmDo2g5zQ==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:uCTmKf9pas9+8tNhhulfTdpyjJhS6+Skv/yutAaCXCC267aTtG4IEA==,iv:t4E1MY94IvnTWguV1I+zcLRds1br225Pq/YLDoCyZrM=,tag:SKiiiF2ymKYKXECsQj388Q==,type:str]
sops:
    lastmodified: "2026-07-05T09:32:15Z"
    mac: ENC[AES256_GCM,data:UgfD2zrkF6Ka9Gtsb/liUURNcsjp61S7HSDaNcHnumU/ZgbBgeBILae3Z0HQCQxS8OnovQyjAD+wRjalprv+ngj50ch2w0XVwE9jU8AA7ie6S2og5329vWziTTMNgwX4AMED6a1Y1zx1nl+1CzUmYNRKW+jZpnpn6+N03unTuWo=,iv:i5bhWleYWjb/Ih718Z1+4UYyi6eBwRrcl/5GH0tgXZk=,tag:kIOLeyYYS1D7NNi2hL/UpQ==,type:str]
    pgp:
        - created_at: "2026-07-05T09:32:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAIMKxA5GsDawKeg74gRKWRtKDJkXDAiTll+WeZdXOIAgw
            EFs8wc1ncxSYF9GmRXV2rc8spHT1YAlBdw0Hq2l8YtWqDxHwprbqXe2jYcVY6cE4
            0lwBOH4/Svhnkq99Y2PIKZVgTG+ALNQPqodcRNXF/gCfIoTyXUPIL0+UemXNcj76
            yWj4ayrH6p/rpL8UVftg7e4SCV48+18egQWMxlR/B3br4sGgjALRMH0E4Bvzeg==
            =yH8R
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
