opencloud_admin_password: ENC[AES256_GCM,data:4/pKBoFwIpP/vI67Y8APeNdqBfjaaxhecaNRtw==,iv:MxOXk4tDsBkAOR/FfdT+OveIG+XtbKUy8ymDqDEPIfI=,tag:eGRf10Jgu2g0xBfuYqoBng==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:25/t/iVZ7I/lypKwTeSQknhQR0aZEsq8m9Y=,iv:E41BGnSGsbeOY62toejRMlM1q2ERPmTNQAubECVyrqI=,tag:QV/BAsK7OuvXq5zOuF8Ixg==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:0x0BBX0O1MzZhmJ6YCVsN86dHA8wBRU3Lif7q65ijut9vF67fsbbZg==,iv:l53hOyEt+C/cb8tAVdrkOb3LPjH/OopjWSR2epwQh/g=,tag:9Jb+NwTJNAbWVENDjbD2eg==,type:str]
sops:
    lastmodified: "2025-10-16T18:02:21Z"
    mac: ENC[AES256_GCM,data:VjvSEkp1TTo8UI3XitRmIeOFWdOsTDFDplz+0ozGmrh9wQNYwZIpG9Xia/RgIfQP56SAuLlgcKGOd/pjeSvO8p1oh8Bbrm6kaABpmDupAjrxxGAAbL93ZQWb0H3u2VwJAiLqnGaAU4iXW2UCiq5K2CZD2zXP/2uVbOGvkUy9kO0=,iv:zD6SXWa5LCpqwOtwOy0lc6juwwZ6PeHbil5nbegWp/U=,tag:gfnqaz3RxTClI+klL0ystg==,type:str]
    pgp:
        - created_at: "2025-10-16T18:02:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdA5vpFJIDlHGRoQV2X5kU0QQlSWPjfRoh9DWD4q48Xe1Uw
            KJObFEpuytGtG7UX0dR0oBONm/DOmsLZknsm6JZVxqMzCtQ5hcz+yyIVr+XZxFV4
            0l4BlPN3oG8BOPL+KM3hrG3+5ArZ3eVTTMkDbhTCjnr7YD767sVtSCFhzIhEmar1
            wm5AiH3S7q3SRb2248izqR9AZLzhhlO020OdmE8q3bgKHtrjJQN8/VPMPHRsXkFI
            =x6q7
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.11.0
