keycloak_db_password: ENC[AES256_GCM,data:20QiQQbpHiwB6CsChc3GbNPXNa58Hxsnh2CYa87lUXpAEw==,iv:viEySbIyyxk5hR1CvIOTwWSDQ0h7JXbuqQ/tCo90bCI=,tag:XpGLPaOq7vmNEqRPdJZjOg==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:+YwFJ5wczRSFp4dhPA9B+jKf430U+9IfOH+Ir+V5MU7+fQ==,iv:zlnZLOp2zdSMGyp1DiPas5FrW3mGIfI0KPluyW4Z4p0=,tag:W6c4lVKlch21U4oIwUXbtQ==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:lwmIUyOh3Gmy+rq42aAiqqP9tB7oDGVQzKs=,iv:iVsJDESM/lNDPwIpZKzS/xkz7NnF7MR5QXH67s0kYKw=,tag:V6n1o5vQebe8YL8QI65YlA==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:3EOEVK7JS9KYzioTHH2HPrYPxpyr7/0MAYk90vVAQfQbLrq2/8nfxg==,iv:epSxXlT/MZ26CduQ3YwZp4j4Z6cYbllgsjeq8qr4/bQ=,tag:oY0AJl3x6dNJ034t2FGxvQ==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:J4JMqt/smboHe0II1nzuPUsDTxhPCTUXzGRuzTKQKTRM+0vRXVUggYVOIjTMF+uCj/o8/wSSWybrRbqy+ErNW1EyvezqSwGLnBY98jDMRJQvl7tgXUfRrs8goxisY2ZZ7T6yj7UnWfZrXKyR071q7crfTsnv5CafekxvpmcNVMo=,iv:AZBJGA890uvQMehYpzBgt3v0UPuXoIF4zpMTEHBE41Y=,tag:zb3QQ0LMnaH6G99hwtM7xA==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdATaqAkYlBsurYAIDnZmyydvJaX4Rpi1N8dK1crzzGr2ww
            57Lo/sL2D1zy7/hLRg8DuGh28E5ZozkaYHZH1W2I7UDZJBMFA+AhZfnEtIHaz03B
            0l4BwfBunRZDGxNSF/WH9KjOAuabRsPeYwRMNbDmHI/rZA7492Z1YUywZnrrY1eD
            g7jC9/fn+NCVV+X6kFFE1LDGwoRPLYs180rcHQFeDJEi926NwGrhu5ao7vVUDLiK
            =4+ng
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
