postgresql_db_password: ENC[AES256_GCM,data:jtlBytfvzDOpXM4nSq3e6Ak0bL6CjCcM+gIAJrH6Zaoxfg==,iv:z2CgzSbjfUnNrfTvC3uFjoZCkeLjBD77B8dnUnGlDc4=,tag:ajJtlVQIuLbeEEFMjRsGTQ==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:qdqynbc4z/qBzTx1gVclX3laRnAMbuLtYtKvZ78rHdS+VQ==,iv:0QxnSNMztQ2Ghte8I0G8KlguT0Kz/kplI2YZarz3NQI=,tag:5iR98O9Y3ePACilloHnO+Q==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:BsLMfui+uaQI6e0GFNhJV44+wHE/YtwfAy0=,iv:PzrdBtYXVKVQNgEWI4WWH6u/6hpL0vr99LPA4uAE3eM=,tag:WXJ3yDc8xekWRfuHus8wlA==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:f82oOpkb5E7dIfiTogOLQFW3xf2NNdbb6rdi0iHQ7OLNIBoHRy4+IA==,iv:R2YJsN4P4wZ2ha2fVvp0st3/M0FpWoLemD0gyzPWMxU=,tag:03BeBh0kZgrl6k4SWiwSow==,type:str]
sops:
    lastmodified: "2026-05-09T14:39:40Z"
    mac: ENC[AES256_GCM,data:xjkBnr/nVq2gHr0fUKr84Vrz0ZhTOTQKFVd6r2+mPHXgEtem3zOGIybG/hcww9s8wh1ox5fr3jgnb8C1sOgsgMJ0js9uanplEye4CjFgt0ieDEHXLbd0sHogyUU+Iv/Ta54Q4DV2bz3fyEACjho8m8t4+tNleVmiMqRfTjeC6k8=,iv:WCBzfQbiGeNwlpZFOw+V5gbkHBgns92JH/eykobcsVI=,tag:ZCyWtjOUTKqSDXigjgVvVQ==,type:str]
    pgp:
        - created_at: "2026-05-09T14:39:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdA+bIDfkjFYL0Kej+kd+ZicSEm1eLjiLfonLB844x5cCgw
            JrbB263OobQUJ+lH0DugSx9/zyeRpAVwLIItv8HXIdnkFSsu6J/VTi8zRwicRSN/
            0l4BYf2f/toa1aZCptJBXBFPcCiFX+Afm94W0SW2YVhX0y+ofhiT2jiy/DED9NIp
            GVb3qUUzZw8U83Xf7nIwCh4xuk1vogWdAPkt98bTOKeG7HDhJguzld1+D0Qtg/mX
            =lJDL
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
