keycloak_db_password: ENC[AES256_GCM,data:h/q3wHzp5Vk4ks9JTRmNgA5dgUEHsyuLLjykR84DL5ecEw==,iv:x4V4A2GDSrdYLG1bxMtGSsdOL+/qsNz6JYbzBDJAJEk=,tag:5xWpk9hBzc/bfNrPyK4Z0A==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:YOeMZiBk0bH9eOTBThZ6XFWCpxl+X8ORR0xWRz3KdGD2cA==,iv:EwQC4I8F2QkS+nhAFGjMtDDsOvPZxmQjUPlGX0AspBw=,tag:7xUp2Jlc1/BCp3iTDl9bSg==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:MKco7yHBm2HPxe809fCNa5QAl0nXtCZHKrI=,iv:B4DDHiJGTj+5EAALQxHFCSpBlQt22MfrpQaqjGoR3Yw=,tag:10oALcb/5HxXMT3KZo4fxQ==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:Vfzd1zmHhw8y58JPu4j3D1Pl9r+Gznif7KYHgVyU3YFAYW9QJbaUkw==,iv:RtyN3n5WOdOqgfn4vOGDHxR+gbaF8rWkBhHt2/y/K3M=,tag:J478n0ZhsVLvdfUmIQRLOg==,type:str]
sops:
    lastmodified: "2026-07-05T09:32:15Z"
    mac: ENC[AES256_GCM,data:c2uY1tD9ulRuS1Az8DICX5/qOVihzhjGQK1VwZIG1uc6pY9e0AHWQxaZ69fbTgzAbjNK+eXuUxEL+7BZronyZkWtE50ewkI/0phfOnyRfDlJQ6TguFI6yoX89ytHOnYeQsEqT/WlJS989EUKaT4rNrD/2GqrnaSbQ/NkRSAYKN8=,iv:Oclr8wxc3V90A9LqUDGxJJxA+J7uGmFfjV4UDCDYqI0=,tag:qYLLKvx2isCYbT9yNERNJA==,type:str]
    pgp:
        - created_at: "2026-07-05T09:32:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAotfg1uvqpbJYW5xvmytulBB2I9fu5VRPqIo3NXjpt1Qw
            09KML7mL858AszIxvZIqz1HCPaz9EyskAMLEWUNs5pWhNonDdz1/8t4S2mVRRLVf
            0l4BcZ3R0xLIYrDk3t/iJDinNwK/Y2GRKI4pn/fhzpU0Cuz7c5GxhU8NRIBpZyPt
            oRqAb9RrISBC4um0saFQ74JwCDTWi8iFQwyNMNGUeSqhouXn14CurQZqyhP8Fch3
            =GpVz
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
