---
podman_user: "container"

######################################
### giftpilz0.container.misc

# Proxy
misc_proxy_enabled: false
misc_proxy_http: ""
misc_proxy_https: ""
misc_proxy_no_proxy: ""

# Network
misc_network_enabled: true
misc_network_driver: "bridge"
misc_network_internal: false

# Network to join even when _network_enabled: false
misc_network_name: "misc-internal"

# Port mapping: host_port:container_port
misc_port_map_enabled: true
misc_port_map:
  - "127.0.0.1:8080:8080"

# Versions
misc_version: "latest"
misc_commit: "db16ab7ca40f6e1e98e6e7a3947fb9e2aa04f527"

# Autoupdate
misc_autoupdate: true
