cfdyndns_api_token: ENC[AES256_GCM,data:NeJtixVNUPWa9HzqNt9ugfkrFq9XR8HSpMYHvN5G9Hasw5ZbL5QeRw==,iv:WY/q4QA4wVeFzM38r2M4/A/lWCSrau+93QU7fPHCxis=,tag:ost80JxhNOm7gotVkGozhg==,type:str]
cfdyndns_update_url: ENC[AES256_GCM,data:RHL98KEkwrga8+O2XryufxBgh4ot445+5SdC8ZP7sXy/wO1Afmx0FQnkcE4IfwQR2W6bjtHDxgSB,iv:5EDOu2+eyZLb3C2Eegd7uVSu4SuEbmFCnV8ZIA/rplQ=,tag:xy9ssmh8Xd86zWcPXjpOvA==,type:str]
sops:
    lastmodified: "2026-05-09T14:39:40Z"
    mac: ENC[AES256_GCM,data:f8Mtyx01IBcevDCAcpyXmFDASL+r3wWKOTz+904GzNnDvoN4ByMB6ngOi3D/uTJtGDjpsSo70WZNrm6C41lZZAPqaHq6nkq9HJuC4R2AmZ/5+9BQsfegOHre8BHJBOrHcsBfEZMnTs9sXw5wmZhfTLn/z5r3gFoT1Tqqg/tQtQg=,iv:Px3BdV9zbK5qSZ3/GfFDB0Q66RW5S0g9SOrmxmfWEyI=,tag:xlXGN8L2MIdlX1x3wssSFg==,type:str]
    pgp:
        - created_at: "2026-05-09T14:39:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAG02jRzD+EIKp9zILJvW7qR57EWyXNdUAqy2vzhOxkmcw
            7ZW5ELn/aFMw6moxuWOVKwsL/9lmplH7EODelQd/gKrptmIty0UP2lUQAJGn+FjE
            0l4BVjRCGLCdABGHnw9dhNM0OBrERG+mHDMP092s2/ABJ6uHMOpj+1n15a57Khq/
            a657NrCJDqtFkQUJNOK1Vl9xUtzPWgZOvdivhXm4zXKe0m/+CmQFSUhE1pkWIxXt
            =EHea
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
