cfdyndns_api_token: ENC[AES256_GCM,data:kmwhI3Xb3iLvnJGxJ0c+lyR/HqZAftxQ2iaKJ7yeSSJE1A33VnRcjQ==,iv:z0lweIJOJYACWIsRQIady1Qla7t3zgjY3wVHV7AZ7vE=,tag:HO5LT5ob/3WvRIXkxuz3aw==,type:str]
cfdyndns_update_url: ENC[AES256_GCM,data:fRCuXIgR0mPNoF7Dz+oxpHdwE/CqD6WbNeafBPbgg9hdCGpmgCMIUeIN6AiYGquS9t701MpAOGjA,iv:KeoUilBSQf94NlPH5DvZp2afROsr/1oxYwJ40/gDtBk=,tag:o+l4dDgt3wMzf8qCb8VEGQ==,type:str]
sops:
    lastmodified: "2026-07-05T09:32:15Z"
    mac: ENC[AES256_GCM,data:3Rv1t/64R7C/4ow20hqjTpHsb7Tc2ORwSESdlWFtdPtnTf23hU2W4FBIseBMYOWr9pZj7LtGYFRmLCl1RudE0weVixZM90ZKAJgu+1C6DuMU8GYF1/7IWrM4L2iAgYjdPoYa7gfK+u8Ai/fRKt1erOiZoMplCIIi0rW+JJQ9rRI=,iv:0O6c04O+NfXZISuplVwivxICiovhadp/1kDFZy11ydo=,tag:VtETea2WDasS4e5Cm5Jurg==,type:str]
    pgp:
        - created_at: "2026-07-05T09:32:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAR4G0eC5CEL99yqDLLCDINDINXacWCN1qYyk4YW+enU4w
            8IDV14Ve5T5hYUOfLTnw8YkY8Vtf6L2nwTRH/ZNNBkvOILcny3m/pfn5JLCKcP6b
            0l4BdCBi7UV9mCTpHXZdeIaJOKF+0TDCp1mXnwM3lz5sfAyka7Ii8p+gFrk8vdie
            U8U+H5ROokt0OUFgVP1+XOfrWBt5Lbhuhas/qtyR0sNVol/m+zTwYjX9TgqG4sfi
            =y2ER
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
