cfdyndns_api_token: ENC[AES256_GCM,data:8b3pSPxfQdh3R5e3nJ49AOdmn3+Mq9Rcrt9lYP5c/Sqi/v3HhbojxA==,iv:bEXDatOU/f2zY8fW7wyKwxRs2+5EgV64A4AEBukvqww=,tag:9Os5iiDxS/gCrhU+ExVBlQ==,type:str]
cfdyndns_update_url: ENC[AES256_GCM,data:TQ9Ha+l0RVW+JhELtX/lHTBSC7M2sGNVExvFi/w78VvA8lJxAVw9tewgjQd6UlbHJnegxvJSsq8G,iv:e+XQBi6ELFnlLrxmYvhHdC9MUqJc8cGtdkH+f0M6W8E=,tag:z0KFj+HrxBtw8320Cai+4A==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:cQxHulNqyYwcLytYIcEgA2o0Wf0lUy3sZIGndEV/fXDPea01YXpYoSxLH3n8A02CaBD97HjCSUoaiqgolmUxuB+K3HHXGmqQ9j6gJPmhOIS8GoPeR5DRt2b3Oz9a4tFxD7WbeJDViuwQrjBeMAUDwwEJeiEWCmIJm6fMZ8ObQWI=,iv:TNDs+wQn4iFOeCR4yWsDHj8uYICmX6nyIW6AAaJM/Xw=,tag:7BGHYLTOL7Ih1Us4Hq1j9g==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAyTJVDlnsiSSsO9PME0F3bE9c08tPDBsBZR33N0nKAmkw
            7WxjUccQNIUNcyvYfw7AvXgi5sW+nAPUrwmA6N136nxzJe4LHqJE/RdvDHD+XJYi
            0lwBoSKXsiI2Bq0Qt2HEJ9cMy+uPO+91Xu5I9qhFgGsP/u/MFkHPKUQnKDGa+abs
            g9+W1Mcp3NdFVgYR5R153XAMfxyRa/7LJQowWQi42jd+brrpL96d5gkkjOH/vA==
            =N/kN
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
