---
collections:
  - name: giftpilz0.container
    source: ../../ansible_collections/giftpilz0/container
    type: dir

  - name: giftpilz0.general
    source: ../../ansible_collections/giftpilz0/general
    type: dir

  - name: giftpilz0.kubernetes
    source: ../../ansible_collections/giftpilz0/kubernetes
    type: dir

  - name: giftpilz0.misc
    source: ../../ansible_collections/giftpilz0/misc
    type: dir

  - name: giftpilz0.server
    source: ../../ansible_collections/giftpilz0/server
    type: dir

  - name: containers.podman
  - name: ansible.posix
