---
- name: "Forgejo: Create Podman config directory"
  become: true
  ansible.builtin.file:
    path: /etc/containers/containers.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "Forgejo: Deploy podman proxy configuration"
  become: true
  ansible.builtin.template:
    src: "forgejo-pod/proxy.conf.j2"
    dest: "/etc/containers/containers.conf.d/proxy.conf"
    owner: root
    group: root
    mode: "0644"
  when: forgejo_proxy_enabled

- name: "Forgejo: Delete quadlet directory"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config/containers/systemd/forgejo-pod"
    state: absent

- name: "Forgejo: Enable lingering"
  become: true
  ansible.builtin.command: loginctl enable-linger {{ podman_user }}
  changed_when: true

- name: "Forgejo: Configure unprivileged port range for rootless containers"
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "80"
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-rootless-ports.conf
    reload: true

- name: "Forgejo: Create quadlet directory"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config/containers/systemd"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0755"

- name: "Forgejo: Create directory structure"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config/containers/systemd/forgejo-pod/{{ item.path }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "templates/forgejo-pod/"
  when: item.state == 'directory'

- name: "Forgejo: Template quadlet files"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/home/{{ podman_user }}/.config/containers/systemd/forgejo-pod/{{ item.path }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "templates/forgejo-pod/"
  when: item.state == 'file'

- name: "Forgejo: systemd daemon reload"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: "Forgejo: Start network service"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: forgejo-network.service
    enabled: true
    state: restarted
    scope: user
  when: forgejo_network_enabled

- name: "Forgejo: Start pod service"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: forgejo-pod.service
    enabled: true
    state: restarted
    scope: user

- name: "Forgejo: Enable podman-auto-update timer"
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    enabled: true
    state: started
    scope: user
