---
- name: Configure hosts - authentik
  hosts: k3s
  roles:
    - role: giftpilz0.general.user
    - role: giftpilz0.general.update
    - role: giftpilz0.general.autoupgrade
    - role: giftpilz0.general.firewalld
    - role: giftpilz0.general.packages
    - role: giftpilz0.homelab.profile
    - role: giftpilz0.general.timezone
    # - role: giftpilz0.kubernetes.k3s
