traefik_acme_email: ENC[AES256_GCM,data:h0Mjp5Jx5v+R76mxIPrSKhFfkHedTuyigIk=,iv:sdV8sQn55/+Yd0aaPNcrkHHYnxTWkvtvUOdfWsbCFPc=,tag:DzcLsLmbY2zTMAE6VeNB8A==,type:str]
sops:
    lastmodified: "2026-08-20T19:39:22Z"
    mac: ENC[AES256_GCM,data:xPlrK7/578uBSD99/+hSXEH4tWSvLUxgu1Y9u75oNUYflndrqrTlbc+JBgAZqwgcd4065XHaP5lo6eDAnWmkMJa3kK5xsiA5CtaJSeejglOZ/9D+Zl98ppcLRWbWIH4rJDtQ4jg+MF7W/EZjYpAHbGY+F1mjp6f3CS+TO1ctK2s=,iv:7wrvFYTaBTQifXogF/0mooprV/JtG0Sj1eBIl3d/nXs=,tag:M3BKfOzbQci24cj14vGlkQ==,type:str]
    pgp:
        - created_at: "2026-08-09T09:44:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdA5cDwlSMsITXPBztK7zc1/Bbp274MCeNjkI76v0o6Olww
            dqroJN3OIFjSIdvxkcf2wkrU6fj3NeH6W7FkqbXf2tOS6JZllW1qFOE1fuBIXpTK
            0l4B0PgTJVwBW7FpFs2XXmLpkZniXiyRssxj6pgtWeLEF3ZCvBsNro9NIHZdSD8b
            EA/jioaih1LDnVsDT7Uwiyo4aqpQfxjuk9MIZuZShERADudklpMY61q/CabSChYJ
            =FeGp
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
