---
argument_specs:
  main:
    short_description: Install and configure the Apache HTTP server.
    options:
      httpd_service_name:
        type: str
        required: false
        description: systemd service unit name.

      httpd_service_state:
        type: str
        required: false
        choices:
          - reloaded
          - restarted
          - started
          - stopped
        description: desired state of the httpd service.

      httpd_service_enabled:
        type: bool
        required: false
        description: whether the httpd service is enabled at boot.

      httpd_package_state:
        type: str
        required: false
        choices:
          - present
          - absent
          - latest
        description: desired state of httpd packages.

      httpd_package:
        type: list
        elements: str
        required: false
        description: list of packages to install.

      httpd_firewalld_zone:
        type: str
        required: false
        description: firewall zone for httpd rules.

      httpd_firewalld_service:
        type: str
        required: false
        description: firewall service name.

      httpd_firewalld_state:
        type: str
        required: false
        choices:
          - present
          - absent
          - enabled
          - disabled
          - skip
        description: desired state of firewall rules.
