monitoring_alloy_loki_basic_auth_password: ENC[AES256_GCM,data:IbwbiH7SD/fuWrtaJZTg0hVuaa9Eezz0yzn0/AV0Ma70sGBbjQeAm54inbY=,iv:N68VyKNTS9Ex+FDkRn/UdblrAzfhkTvSEH9EK07rZUI=,tag:za3k9k1V3inrez2Tcu+aaw==,type:str]
monitoring_alloy_mimir_basic_auth_password: ENC[AES256_GCM,data:titamb4Qyefx7p61mv3XNxQKQZpg9FGEUUPqqwBF78Z7w+PHYhC9GUa+kuw=,iv:LY88zO7ncvWuR/BSChsxyhQ/v+wg4MVnX+6t54EDu9E=,tag:whkT17InOJQUmUqi3zHapQ==,type:str]
monitoring_stack_loki_basic_auth_user: ENC[AES256_GCM,data:SuY9MzM=,iv:TPq9O7dJjx1dgGKuGnV52M+iaC8TMHPUsckAuYtnAUY=,tag:OSmNhJr7zATKHWj6teigwA==,type:str]
monitoring_stack_loki_basic_auth_hash: ENC[AES256_GCM,data:5kElqoTq/1X5VcrYkdGzwgq8zpiu1qtafTqocgzmEzkGPktYjZOB4M5pmJbgtoplKiYogPMSPF/jQb+R,iv:nIk3wYoqj8hOJmyCYn78lrRiLDGFnzaX9a3VstwMrHs=,tag:SE7r/8tPK0q4OylU8pK5Gg==,type:str]
monitoring_stack_mimir_basic_auth_user: ENC[AES256_GCM,data:fAYG7FQ=,iv:zehpGaQFF/UVjT4cbaa52OgTyq4TyUAByg6Md429cLs=,tag:KXgF8xZPyF+G+ZuHx3X9UA==,type:str]
monitoring_stack_mimir_basic_auth_hash: ENC[AES256_GCM,data:O478xtBRoAZtF+ssNq9hIiFfxy2TT3bU4EyTjY/loXmomcaQsrjS79g9R7kHcpOhJ+ZsugxIYjubZjyS,iv:UW7gURFbACJ1dQK34yGrIQLRXr+4zTJxEmED3gLN2mA=,tag:QEMjxHInaWLMWVEz8BE/FQ==,type:str]
monitoring_stack_perses_oidc_client_secret: ENC[AES256_GCM,data:rHhYRDcSz3TY0bliOOF3nZPFGB3xoxjyaneckToYAzRM9eEVMnJR+tv9Ub1xI85+UTQRsydoiYc2/bRRo+KSUg==,iv:tyEXzQPmqmNFcaYKuWIwDCQFTdWiwycr0/gHzo6CyKg=,tag:ZfcY6uKnl4CIzBcuDazT5Q==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:U0d+y6jW8OhWGnulEzutB5NniFF7IjbyBJemkj+m4im6+48PZ8t9QXnVChzpRSjU8RZ9DbYsCJ1VlavuWvM0u/m28Diz1bgX9735DPFTpIP2ROa+dDHXuReMtSPbY+JGcsjCv8VqAxRYjyf+SAs+E7CE6z3VxxJW26ZR8Ns0Knk=,iv:oAAp5D2qfC+pQyhwRNgeA8fzb/Xag7mIszx5g+/Qq3w=,tag:/sCYKXDzdIM0JQ/mqCl9TQ==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdA17Vph6Af6LYb2aO60ieFbgxH5VF3wuFXBzU0Glf+mkUw
            xjAam/E3yull2es/ngGbEcCx+CpGU6AKdzsnS74Pink3TUOmmq8VZ/5n1xmxOYeN
            0l4Bj40ExFgRgqQc27bQvtKTavZeaCfq5m/bV5jroWJ1xu4Kwjxpx15tRTIoM7AT
            dsMnetAtnJ5LXsvwNfKDYUctQmr1E0C6zAh3hB29E1TadX7Ze5/qCtL+upYIWbUg
            =hb3j
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
