---
argument_specs:
  main:
    short_description: The main entry point for the monitoring role.
    options:
      monitoring_agent_config_remoteserver_loki:
        type: str

      monitoring_agent_config_remoteserver_prometheus:
        type: str

      monitoring_alloy_loki_basic_auth_username:
        type: str

      monitoring_alloy_loki_basic_auth_password:
        type: str
        no_log: true

      monitoring_alloy_mimir_basic_auth_username:
        type: str

      monitoring_alloy_mimir_basic_auth_password:
        type: str
        no_log: true

      monitoring_agent_external_labels:
        type: dict

      monitoring_alloy_traefik_scrape_enabled:
        type: bool

      monitoring_alloy_extra_config:
        type: str
