---
######################################
### roles

- name: Configure hosts - lb
  hosts: lb
  vars_prompt:
    - name: user_password
      prompt: Select password
      private: true
      confirm: true
      unsafe: true
  tasks:
    - name: "Lb: Set facts"
      ansible.builtin.set_fact:
        user_password: "{{ user_password }}"
  roles:
    - role: giftpilz0.general.user

- name: Configure hosts - common
  hosts: all
  roles:
    - role: giftpilz0.general.update
    - role: giftpilz0.general.dnf
    - role: giftpilz0.general.firewalld
    - role: giftpilz0.general.packages
    - role: giftpilz0.general.timezone
    - role: giftpilz0.general.monitoring
    - role: giftpilz0.server.cockpit
  tasks:
    - name: "Cockpit: Generate SSH key pair"
      community.crypto.openssh_keypair:
        path: /home/{{ ansible_user }}/.ssh/id_cockpit
        type: ed25519
        mode: "0600"
        state: present
      when: inventory_hostname in groups["lb"]

    - name: "Cockpit: Fetch public key from the control node"
      ansible.builtin.slurp:
        src: /home/{{ ansible_user }}/.ssh/id_cockpit.pub
      register: public_key
      when: inventory_hostname in groups["lb"]

    - name: Store publickey
      ansible.builtin.set_fact:
        token: "{{ public_key.content | b64decode | regex_replace('\n', '') }}"
      when: inventory_hostname in groups["lb"]

    - name: "Cockpit: Add the public key to all nodes"
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ hostvars[item]['token'] }}"
      loop: "{{ groups['lb'] }}"
      when: inventory_hostname not in groups["lb"]

- name: Configure hosts - lb
  hosts: lb
  tasks:
    - name: "Lb: Enable vrrp"
      become: true
      ansible.posix.firewalld:
        rich_rule: rule protocol value="vrrp" accept
        permanent: true
        state: enabled
        zone: block

- name: Configure hosts - lb (MASTER)
  hosts: lb[0]
  tasks:
    - name: "Lb (MASTER): Set facts"
      ansible.builtin.set_fact:
        keepalived_config_state: MASTER
        keepalived_config_priority: 255
    - name: "Lb (MASTER): Install keepalived"
      ansible.builtin.import_role:
        name: giftpilz0.server.keepalived

- name: Configure hosts - lb (BACKUP)
  hosts: lb[1]
  tasks:
    - name: "Lb (BACKUP): Set facts"
      ansible.builtin.set_fact:
        keepalived_config_state: BACKUP
        keepalived_config_priority: 200
    - name: "Lb (BACKUP): Install keepalived"
      ansible.builtin.import_role:
        name: giftpilz0.server.keepalived

- name: Configure hosts - container
  hosts: container
  roles:
    - role: giftpilz0.server.podman

- name: Configure hosts - monitoring
  hosts: monitoring
  roles:
    - role: giftpilz0.server.podman

- name: Configure hosts - nfs
  hosts: nfs
  roles:
    - role: giftpilz0.server.nfs

- name: Configure hosts - k3s
  hosts: k3s
  roles:
    - role: giftpilz0.kubernetes.k3s
