# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# =============================================================================
# ENTRYPOINTS
# =============================================================================
entryPoints:
  web:
    address: ":{{ traefik_http_internal_port }}"
{% if traefik_http_redirect_https | default(true) %}
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
{% endif %}

  websecure:
    address: ":{{ traefik_https_internal_port }}"
{% if traefik_transport_timeouts_enabled | default(false) %}
    transport:
      respondingTimeouts:
        readTimeout: "{{ traefik_transport_read_timeout }}"
        writeTimeout: "{{ traefik_transport_write_timeout }}"
        idleTimeout: "{{ traefik_transport_idle_timeout }}"
{% endif %}
    http:
      middlewares:
        - security-headers@file

{% if traefik_tcp_entrypoints is defined %}
{% for entrypoint in traefik_tcp_entrypoints %}
  {{ entrypoint.name }}:
    address: ":{{ entrypoint.internal_port | default(entrypoint.port) }}"
{% endfor %}
{% endif %}

{% if traefik_acme_enabled %}
# =============================================================================
# CERTIFICATES RESOLVERS
# =============================================================================
certificatesResolvers:
  default:
    acme:
      email: "{{ traefik_acme_email }}"
      storage: "/acme/acme.json"
      caServer: "{{ traefik_acme_ca_server }}"
{% if traefik_acme_eab_enabled %}
      eab:
        kid: "{{ traefik_acme_eab_kid }}"
        hmacEncoded: "{{ traefik_acme_eab_hmac }}"
{% endif %}
{% if traefik_acme_challenge_type == 'dns' %}
      dnsChallenge:
        provider: {{ traefik_acme_dns_provider }}
        propagation:
            delayBeforeChecks: 60
{% elif traefik_acme_challenge_type == 'http' %}
      httpChallenge:
        entryPoint: web
{% elif traefik_acme_challenge_type == 'tls' %}
      tlsChallenge: {}
{% endif %}
{% endif %}

# =============================================================================
# PROVIDERS
# =============================================================================
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

# =============================================================================
# LOGGING
# =============================================================================
log:
  level: {{ traefik_log_level }}
  format: {{ traefik_log_format }}

accessLog:
  format: {{ traefik_access_log_format }}
  bufferingSize: {{ traefik_access_log_buffer_size }}
