---
- name: Configure hosts - common
  hosts: all
  roles:
    - role: giftpilz0.general.user
    - role: giftpilz0.general.update
    - role: giftpilz0.general.autoupgrade
    - role: giftpilz0.general.firewalld
    - role: giftpilz0.general.packages
    - role: giftpilz0.homelab.profile
    - role: giftpilz0.general.timezone
    - role: giftpilz0.server.podman

- name: Configure hosts - authentik
  hosts: authentik
  roles:
    - role: giftpilz0.homelab.traefik
    - role: giftpilz0.homelab.authentik

- name: Configure hosts - forgejo
  hosts: forgejo
  roles:
    - role: giftpilz0.homelab.traefik
    - role: giftpilz0.homelab.forgejo

- name: Configure hosts - homeassistant
  hosts: homeassistant
  roles:
    - role: giftpilz0.homelab.traefik
    - role: giftpilz0.homelab.mosquitto
    - role: giftpilz0.homelab.homeassistant

- name: Configure hosts - opencloud
  hosts: opencloud
  roles:
    - role: giftpilz0.homelab.traefik
    - role: giftpilz0.homelab.opencloud

- name: Configure hosts - vaultwarden
  hosts: vaultwarden
  roles:
    - role: giftpilz0.homelab.traefik
    - role: giftpilz0.homelab.vaultwarden
