restic_repo_password: ENC[AES256_GCM,data:ZzBeEpQkf/TAwXDrlcKzCO9OjfG/36GMItN0iyRW,iv:3mLkNciXGWxkyguGHK8HKAFZjUnR+4kqY0HhNQHAT6s=,tag:8mVYGjMkteyUsnJRcmO4AQ==,type:str]
sops:
    lastmodified: "2026-05-09T15:27:11Z"
    mac: ENC[AES256_GCM,data:gn1nnghKpWEkzGyJO3NiasSZKur7YwuPYGhhIMUSGmRWByJxPVGerv08vgTypws0VHNcL1PYdVqPSGJXCCAxwzAQoTgwpRvq/MRSz7q0Z8EbYmvd+kKMleoyK3qEpQ5ARAgTN2yU7xrxBclFHze+XQYbT+AtSZl1eXYfxvSj+fo=,iv:sqrKXUJYt0DqUQzbEeZ7L+/AyOOXbYvta5kg41aPtfw=,tag:h+IvjVz9MO3rLtXgWio2uw==,type:str]
    pgp:
        - created_at: "2026-05-09T15:27:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAx4zhaiCnG+WSg4ijH6bAvypOTz1BSiqceTguBhOuFyUw
            adNEDDflqaTHNO5NVO8+jZ6MeIT+t5jV6A9niCne0jLTiqnWc1L4ExKaNtwBIuez
            0lwBH5pqK4MjA3mkq6YeE8ub3KYkGzcSa28tn/oqqf1FMAD8tEwEfaDxllQzKy9G
            SA9tnkmSQL/B+cSSePiysHuDEp6yYfSn1XXZMR6A/QxJEglRI21m7IaCg0+hvA==
            =mDiQ
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
