---
# yamllint disable rule:line-length

######################################
### giftpilz0.general.timezone

timezone_timezone: Europe/Berlin

######################################
### giftpilz0.general.packages

packages_rpmfusion_package_state: skip
packages_python_package_state: skip
packages_flatpak_repo_state: skip

packages_additional_package:
  - whois
  - nmap
  - bash-completion
