---
# yamllint disable rule:line-length

######################################
### giftpilz0.general.timezone

timezone_timezone: Europe/Berlin

######################################
### giftpilz0.general.packages

packages_rpmfusion_package_state: skip
packages_python_package_state: skip
packages_flatpak_repo_state: skip

packages_additional_package:
  - whois
  - nmap
  - bash-completion

######################################
### giftpilz0.general.user

user:
  - user_username: "backup"
    user_groups:
      - backup
    user_home: true
    user_shell: "/bin/bash"
    user_comment: "backup"
    user_install_key_to_targets: false
    user_sudo_pwless: false
    user_state: present
    user_password: "!"
    user_pub:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOAhl7NUVzPjYfk/rB+dS0i6wDPkB5EtlZSfVwGdrWsg"
