mosquitto_users:
    homeassistant: ENC[AES256_GCM,data:DDo80KMWqufojTO2Y8xNxwpfREynx5H2Um4VUjiK,iv:4IZQ5IA1hKI0X4jPTS12W5+e/NZ7g1oVfb3aJhSi0+0=,tag:H5SmNnKboI7d9ju8QITVzg==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:H8a7U09DsJp2Wxo0mKdzXNi/KxqzVQeD8n4=,iv:VdW2/AvmVHBV7uZUG1R+bjtpKrsORdmqoBNBslOCP+8=,tag:1WDiscCh7B29+nZ3Z0srCA==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:jzfrdWq9UYta6ejzn4BIQ/joBP7oG/v8hVsgasv8InCcVy4FP/r41A==,iv:/ykcDTjX5mjL5LqKw9Bev/tNA4ASPlVxam8l4/dDR+k=,tag:D03VQaa1b2TFmpf2DJdXzQ==,type:str]
sops:
    lastmodified: "2026-09-05T14:43:07Z"
    mac: ENC[AES256_GCM,data:HD5SMbekJV/g9a0cNupW1G9GvM3eIgNe5u7Sjr9UprrJn3SfpZnkykooZmkgZQC5JuPVXpDZ6/SUgRhfLo8Xx479BLfzakh7K+I0o/FEdo8UCAnFWRIipEByHgXz+vfv80t5/roeZSXIixw2aR2DKD4AxF4S2sdhgg5wDSPMwrs=,iv:N250UzoJrl0cv3ZWNkzKRcU07CbqqpMWRL/eb4O6vzI=,tag:k9ZXuQv55fvyE4h6inUIuQ==,type:str]
    pgp:
        - created_at: "2026-09-05T14:43:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAt3Iu5CRdgeVzmnuaqZg6UxjEBD+Qq0D/u0SpITLsTygw
            VVSaO1A615sBXrdTdWIMo6k6fQLeKH6wv8B1t/2Dp+F+buJqQQSg9fghk1V+divG
            0l4BpG0oP2HjM6ep+VI6GxuD3fBzA4q+FxpiF/kgaL2vnVdzDLFWtuRo3itDOQdd
            xEa1YVr0u8DnYbxzPJSKu6tWmZowEWW1L6k1Mx2mcCNVZpn8Swcqq+OBlYxN7OYF
            =UAQm
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
