mosquitto_pwfile_users:
    homeassistant: ENC[AES256_GCM,data:xYzQOmgh43TXuOt/naFIn1wH7kpg4vMqT5GlQwSQNbvyCBFNO7UWsViilLbPsF83dpGD2vetFyRZJAy+qpHzAi+J5MCHo2e28GAQEB7eJ6ZHHDcbLpMNATq0ONUCZw/OeJJ/EzhMHVKAQwilvPkhjg==,iv:M/g7xLCWg0TJ1WAiyKA59aSH45GpHAROlnBRp5ZNw+Y=,tag:iSgicmfUsGfOdk25GXRoRg==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:eNaKTN4waVnB3AiHqQuPzJ9XRvL9al6DbI0=,iv:4cRK14v4pvBzTRUXnsyTQr/KiVuuDvTVQSY37liCe/8=,tag:xrO5q6sp311KUthe0wTk7g==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:wwjPc18L6koSGCfydz7pvmLpOzYNG6WK92uTojzocQhjMQv1yBuynQ==,iv:JW44YYu09ScGFr8JfFtDo50k9jYH7G0SA0wtUyhQLiY=,tag:GjpPxNruiew+K+431whPog==,type:str]
sops:
    lastmodified: "2026-07-05T09:32:15Z"
    mac: ENC[AES256_GCM,data:he/Hn+uUolN3ZFQsTd2k28PuIj+gMyMRAhYX92HO20GNMv+xbvnnNN4ZLcQUG8naGii8VXwg5bjCEFlwNGmoPf3e5Kl+K7vNxr+h+OYvSY1ToI9IqWCYkImJhSsh0lt4REud5S+bbaySA3c/Cj0rSY/GQcsQSTII+A37ndK10H4=,iv:TkZuUATWpaty+QDLXaHhNhEZClQSHQG3jTf3/gtkLR0=,tag:AkcOwDDBpPNrCbA89cPzGQ==,type:str]
    pgp:
        - created_at: "2026-07-05T09:32:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAnV4oLZ/YERX5G98wCoyljpygs/3VLp+tzJvUBuv66yUw
            2GcSUxspH9QTLzAroIlQoRC/B6x5LSEA6ahRWx5soKiqaCCsHocw1hkm5hRIRjeB
            0lwBMsf0kKuSLZMD+kF54BQyfQTEdiH//RvGFhB/qizJlyqu/UKxAVadQDTJTbbV
            TZVFEsS1MKkKKHHJmGDUVboXAi0mzdg5jnlB9wMxpAFw7OaVOLd1LSFwzaL65Q==
            =YWX9
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
