mosquitto_pwfile_users:
    homeassistant: ENC[AES256_GCM,data:QZUqY3iSB0srF+jv4OebGjkgXHbZQMF/PKXFZ25xZnnbJiNfF2frVmgWA9E02hrNgwos39P8l5odTjKAEUnpfUvIFNLpl6CR0YoYy5AghKJrQAApwdqEjIUbeXrBozf8mXPWyOzIDG+H7PH+e75saQ==,iv:+jpjlU/KRn/ZkAeOGtd5LFGlGqCKiWPUooQ2N4OSLCo=,tag:w+WAn1BTfBWhphNpoEC85w==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:Q79K54oCrS9+SkDxK4GwGlSkKiUJQQQc7qk=,iv:X3mroYikMhYhF1hKsrmxW0PQSwNagxopph7bkabKRZ0=,tag:JRz9Xq0i1TNmDIFZ95/viQ==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:NacSbZPKXLRbztA/7KQgN6+In64pOUjoRTjXBtnSXemREk8rts4WEQ==,iv:fepESpddk3lEM/Vu9SyXG9/MzgeLsURR0VcfqQYGywQ=,tag:KNBmEWG6gr8/dnOBOmD9gQ==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:xP8Gf3W5RmHiDL5JS5dsMtdFL8oclNNWRl4jrk8Q2fWiyT+vBmBzBd5VNDGQ/6zODiKnFQurKasJTefs5l6xgYAmo8vSTlNyY5WZt9UTkgz0XJ3iBpb8JrmVn1xhq8TAnxjt+A33v4NBCoZTQV8pso5kBYbM3zYsL/g49fzz5e8=,iv:L42cdklVm5N2r29Ulb0Xilpoi7zw7dfMcLI8sbxkOxw=,tag:AphwcFTPV7Sfa4Hhj8L7fQ==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAsK9EN8UCF/xVwFTJ0tPV+IZBoeXU8fYWiMHjOcz2Lg4w
            byzyyn9C1egdaoggva7EIbiHojSunAYGmA2W/5/yfFSdPXkVR6crRa6K7z3IySJp
            0l4B1iYVc8cOmJiQAIK5i8KoO6nwJIhprF2oa6590XS4yJXr+MsOaMF5UF9mNCrw
            s1qG+7TINGWZBDbnGDOkQhgjL/Qbp2u0RwPLPGlQ0xQU5rlj6LONki2lxymbHsd7
            =qeQi
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
