---
server:
  children:
    nfs:
      hosts:
        192.168.60.230:
    k3s:
      hosts:
        192.168.60.231:
        192.168.60.232:
        192.168.60.233:
    dns:
      hosts:
        192.168.60.222:
    container:
      hosts:
        192.168.60.221:
    cockpitmanager:
      hosts:
        192.168.60.220:
  vars:
    ansible_port: 22
    ansible_user: serveradmin
