---
server:
  children:
    nfs:
      hosts:
        192.168.178.230:
    k3s:
      hosts:
        192.168.178.231:
        192.168.178.232:
        192.168.178.233:
    podman:
      hosts:
        192.168.178.221:
    cockpitmanager:
      hosts:
        192.168.178.220:
  vars:
    ansible_port: 22
    ansible_user: serveradmin
