---
server:
  children:
    k3s:
      hosts:
        192.168.65.231:
    lb:
      hosts:
        192.168.70.101:
        192.168.70.102:
    container:
      hosts:
        192.168.60.221:
  vars:
    ansible_port: 22
    ansible_user: serveradmin
