---
server:
  children:
    nfs:
      hosts:
        192.168.60.230:
    k3s:
      hosts:
        192.168.60.231:
        192.168.60.232:
        192.168.60.233:
    monitoring:
      hosts:
        192.168.60.223:
    lb:
      hosts:
        192.168.70.101:
        192.168.70.102:
    container:
      hosts:
        192.168.60.221:
  vars:
    ansible_port: 22
    ansible_user: serveradmin
