---
- name: Configure hosts - forgejo
  hosts: forgejo
  roles:
    - role: giftpilz0.general.user
    - role: giftpilz0.general.update
    - role: giftpilz0.general.autoupgrade
    - role: giftpilz0.general.firewalld
    - role: giftpilz0.general.packages
    - role: giftpilz0.homelab.profile
    - role: giftpilz0.general.timezone
    - role: giftpilz0.server.podman
    - role: giftpilz0.homelab.traefik
    # - role: giftpilz0.homelab.forgejo
