server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "homelab.local"
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
    authorizer = "root"
    admission_webhook_enabled = false
}

plugins {
    DataStore "sql" {
        plugin_config {
            database_type = "sqlite3"
            connection_string = "/run/spire/data/server.datastore.sqlite"
        }
    }

    NodeAttestor "join_token" {
        plugin_config {
        }
    }

    KeyManager "disk" {
        plugin_config {
            keys_path = "/run/spire/data/keys.json"
        }
    }

    UpstreamAuthority "disk" {
        plugin_config {
            key_file_path = "/run/spire/data/upstream_ca.key"
            cert_file_path = "/run/spire/data/upstream_ca.crt"
        }
    }
}
