monitoring_alloy_loki_basic_auth_password: ENC[AES256_GCM,data:4ahmXjQC6rdpnHWiLbjDHiy/yi8S1LPWAsfmkGInFl7RiwE1MCR837zYGlM=,iv:8IuigkNPQ4L5UxupGrFC4gMRB9MGF/w9EDE1075c1aA=,tag:31AmbNZjpt7I4OMGf/byrw==,type:str]
monitoring_alloy_mimir_basic_auth_password: ENC[AES256_GCM,data:dMjhSlfeuBYWH/gVolTP97n6VS1lw1CSoIK3IZgR9wl3KpHJFLe/Q9rEIFA=,iv:qUnVi8K4KFTvl3oQ2sCY8iQd8Lly3DV3B25ClUFql/M=,tag:DF/cf+JtobwMRFwbrBZZsQ==,type:str]
monitoring_stack_loki_basic_auth_user: ENC[AES256_GCM,data:ktdo5T0=,iv:WYp0JF3VVj1RBl6SwYWyj4W0jrYKLvVCnIgfQ9qDjFY=,tag:esvJgCeaX0q+XLnrWig6Lg==,type:str]
monitoring_stack_loki_basic_auth_hash: ENC[AES256_GCM,data:Ha3TQ7WhZDkvbw7aEaVyJCWrrZCRiUSq/fNz9HsfPUJ2RHA26xZopkUEPgTiz4c/5Yu051qBdcOAONuG,iv:SIzYvXo93KTksYY3k8vi8l3AjHrKu1e37dfLeaWGNt0=,tag:7qQJGR+rDicqSHAnTxCvhg==,type:str]
monitoring_stack_mimir_basic_auth_user: ENC[AES256_GCM,data:bXf/9ds=,iv:neoTRXHjqV61jjxL0YyqTvfr+QjFbuB3vs6q9Dn9LW8=,tag:EmZ18mWN/kJdkwxHp/jJtg==,type:str]
monitoring_stack_mimir_basic_auth_hash: ENC[AES256_GCM,data:jV99BK5RF1Es5OlBVcpmEYVEvCKGeFiCiDAr68pVowZFoYecNyBoM03X9jwJ8Jdk10wKEezAzp6TRkhE,iv:hYfE2SXErAMxrfRluPxmvPxNUjZS5/2GPGbbkDOwqVY=,tag:5qifkHWnMqVfedYnc02nRw==,type:str]
monitoring_stack_perses_oidc_client_secret: ENC[AES256_GCM,data:a25CjNVCbrsppVs6BKiQV6nTJvt+Xkj11NRmqkhTPnQb60EG2FB6RgCSad1Txc1aoMYzM/CxDwmLR66nP9m0eg==,iv:ZB1ZSu5vAkzAqOxLreaW7qHyNLTv6u40lhMxuHglap8=,tag:n1FqIq+RB6HeGZ6ErUtswg==,type:str]
sops:
    lastmodified: "2026-08-02T12:10:51Z"
    mac: ENC[AES256_GCM,data:+iMtPD1AnZKyySkbHd73f0Cys5+jkmUvLbkdfylRGkKZiv01gYr+ubf6R+KBPkUnsfni7IFxc07LuwRh1VQbR7C7Kj+AWlSt/tEqXtZQQOyEdh3IBBc1x00C+bxXnYFfo4Tlp5BUhxQwpwBx9MznucqSfv6Z/LItdXz0xW9kI90=,iv:sxRHiFwLPriFIHl2AB6czs0NM6THrE8ridNcDdT2lo4=,tag:h20qCJ9xNcnA1tmZE84EVg==,type:str]
    pgp:
        - created_at: "2026-08-02T12:10:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAKo5lE3fBVMdxehLVzk7CTzBj3IjmM5RUxyAxUHKJCxkw
            3xZLou0Mc9u/kI+tKw7L9bEDCyH8DTkXOCMKQ9LgTQpbuamPrEy7xSHqFtqZGEia
            0l4BN0YjPBk5q6VdSvSbFKyXvJldos3mcgUGOe+2XDyqaRROpR7Nst7V2Xa3szU4
            lsoAOv//l/f7RP6TtmbGcv0JKWHZXpzA8iCE4st2T+QbLd22g13u1P4hStHOlSy6
            =AzQI
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
