k3s_token: ENC[AES256_GCM,data:4PxwT17WISo=,iv:tGx9IvmBBKTQcCaZyExjauBJbcbBGg933tL/zFwytQw=,tag:owHr0nMBzCcDHsmYFdnsXA==,type:str]
sops:
    lastmodified: "2026-05-09T15:31:56Z"
    mac: ENC[AES256_GCM,data:0xrMTL7wMNvbefej9cQRXSqKBGgx0faxH/Qf1+aCNIrpHzsRSCjU0jLTRBqO1z0RV5cFJlPXXLFekwubR7LeqvTwg3F5CS0xFXf7x3DHTa9hdeMf6vkLESR5OLIwKLDyOM1u2J+VDp/f8MqlZMiGgkosRaZSju05ypsDU3hbuaM=,iv:XuWGz3sBHq6F4V23VmvVQ0RH1C2NCr3jo0Bm1d011FU=,tag:8nzhNR3+kapIU1bOieLa1Q==,type:str]
    pgp:
        - created_at: "2026-05-09T15:31:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAF7unv4JJLFBJw3RwkQqbaT29T5w4KF6okHhpyFiZ4h4w
            956XoM0AULgcaSIAq66V9wxpSpwTV9oeFziPI9xrTZMmwBnIpW055u7gZucpL7n2
            0l4BLBHtJV4QBkGfuvCdo5Frd3YJ8WQR4RleNvudMLX1G4xStUoWLV+3u6LewfUz
            9Zh13xfKtrAw8NPGpzfEHrGM/4UTQ5dKHxE5IuYPc8Zc/dNKtxM7HRUGfrsUj5QM
            =aOcN
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
