agent {
    trust_domain = "homelab.local"
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/run/spire/agent/agent.sock"
    trust_bundle_path = "/run/spire/data/bundle.crt"
    allow_bare_attestations = "true"
    allow_unverified_spiffe_ids = "true"
}

plugins {
    NodeAttestor "join_token" {
        plugin_config {
        }
    }

    KeyManager "disk" {
        plugin_config {
            directory = "/run/spire/data"
        }
    }

    WorkloadAttestor "unix" {
        plugin_config {
        }
    }

    WorkloadAPI "workload" {
        plugin_config {
            workload_socket_path = "/run/spire/agent/workload.sock"
        }
    }
}
