---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: server
    source: 192.168.60.0/24
  - zone: loadbalancer
    source: 192.168.50.100
  - zone: loadbalancer
    source: 192.168.50.101
  - zone: loadbalancer
    source: 192.168.50.102

firewalld_rules_services:
  - service: cockpit
    zone: loadbalancer
    state: enabled
  - service: ssh
    zone: loadbalancer
    state: enabled
