---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: server
    source: 192.168.60.0/24
  - zone: loadbalancer
    source: 192.168.70.100
  - zone: loadbalancer
    source: 192.168.70.101
  - zone: loadbalancer
    source: 192.168.70.102

firewalld_rules_services:
  - service: cockpit
    zone: loadbalancer
    state: enabled
  - service: ssh
    zone: loadbalancer
    state: enabled

firewalld_rules_ports:
  - port: 30000-30050
    protocol: tcp
    zone: loadbalancer
    state: enabled
  - port: 30000-30050
    protocol: udp
    zone: loadbalancer
    state: enabled
