---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: work
    source: 192.168.10.0/24
  - zone: cockpit
    source: 192.168.60.220
  - zone: kubernetes
    source: 192.168.60.231
  - zone: kubernetes
    source: 192.168.60.232
  - zone: kubernetes
    source: 192.168.60.233

firewalld_rules_services:
  - service: ssh
    zone: work
    state: enabled
  - service: cockpit
    zone: work
    state: disabled
  - service: cockpit
    zone: cockpit
    state: enabled
  - service: ssh
    zone: cockpit
    state: enabled

######################################
### giftpilz0.kubernetes.k3s

k3s_token: changeme
k3s_version: v1.30.2+k3s1
k3s_vip_api_endpoint: 192.168.60.234
k3s_extra_server_args: --tls-san {{ k3s_vip_api_endpoint }} --flannel-backend=none --disable-network-policy --disable traefik --disable servicelb --selinux
k3s_kube_vip_tag: v0.8.1
k3s_kube_vip_iface: eth0
