---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: server
    source: 192.168.60.0/24
  - zone: loadbalancer
    source: 192.168.70.100
  - zone: loadbalancer
    source: 192.168.70.101
  - zone: loadbalancer
    source: 192.168.70.102
  - zone: kubernetes
    source: 192.168.65.231
  - zone: kubernetes
    source: 192.168.65.232
  - zone: kubernetes
    source: 192.168.65.233

firewalld_rules_services:
  - service: cockpit
    zone: loadbalancer
    state: enabled
  - service: ssh
    zone: loadbalancer
    state: enabled

firewalld_rules_ports:
  - port: 6443
    protocol: tcp
    zone: kubernetes
    state: enabled

######################################
### giftpilz0.kubernetes.k3s

k3s_token: changeme
k3s_version: v1.33.0+k3s1
k3s_vip_api_endpoint: 192.168.65.234
k3s_extra_server_args: --tls-san {{ k3s_vip_api_endpoint }} --service-cidr {{ k3s_service_cidr }} --cluster-cidr {{ k3s_cluster_cidr }} --flannel-backend=none --disable-network-policy --disable-helm-controller --disable metrics-server --disable servicelb --disable traefik --selinux

k3s_kube_vip_tag: v0.8.10
k3s_kube_vip_iface: eth0
k3s_service_cidr: 10.43.0.0/16
k3s_cluster_cidr: 10.42.0.0/16

cilium_version: 1.17.4

cilium_config_kubeproxyreplacement: true
cilium_config_k8sclientratelimit_qps: 30
cilium_config_k8sclientratelimit_burst: 150
cilium_config_rolloutciliumpods: true
cilium_config_l2announcements_enabled: true
cilium_config_ingresscontroller_enabled: true
cilium_config_ingresscontroller_default: true
cilium_config_gatewayapi_enabled: true
cilium_config_hostfirewall_enabled: false
cilium_config_hubble_enabled: true
cilium_config_hubble_relay_enabled: true
cilium_config_hubble_relay_rolloutpods: true
cilium_config_hubble_ui_enabled: true
cilium_config_hubble_ui_rolloutpods: true
cilium_config_ipam_operator_clusterpoolipv4podcidrlist: ["{{ k3s_cluster_cidr }}"]
cilium_config_ipv4_enabled: true
cilium_config_ipv6_enabled: false
cilium_config_egressgateway_enabled: false
cilium_config_operator_enabled: true
cilium_config_operator_rolloutpods: true
