---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: server
    source: 192.168.60.0/24
  - zone: work
    source: 192.168.10.0/24
  - zone: work
    source: 192.168.15.0/24

firewalld_rules_services:
  - service: cockpit
    zone: work
    state: enabled
  - service: ssh
    zone: work
    state: enabled
  - service: http
    zone: work
    state: enabled
  - service: https
    zone: work
    state: enabled

firewalld_rules_ports:
  - port: 30000-30050
    protocol: tcp
    zone: work
    state: enabled

######################################
### giftpilz0.general.user

admin_group: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"

user_key_target_users:
  - root

user:
  - user_username: "{{ ansible_user }}"
    user_groups:
      - "{{ admin_group }}"
      - "{{ user_username }}"
    user_home: true
    user_shell: "/bin/bash"
    user_comment: "{{ user_username }}"
    user_install_key_to_targets: true
    user_sudo_pwless: true
    user_state: present
    user_password: "{{ user_password }}"
    user_pub:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOAhl7NUVzPjYfk/rB+dS0i6wDPkB5EtlZSfVwGdrWsg"

######################################
### giftpilz0.server.keepalived

keepalived_config_path: /etc/keepalived/keepalived.conf
keepalived_config_virtual_ip: 192.168.70.100
keepalived_config_interface: eth0
keepalived_config_virtual_router_id: 100
keepalived_config_vrrp_instance: VG

######################################
### lego

lego_keytype: rsa4096
lego_cert_path: /etc/ssl/lego
lego_acme_email: ""
lego_dns_resolver: "8.8.8.8:53,1.1.1.1:53"
lego_acme_provider: cloudflare
lego_cloudflare_api_key: ""
lego_manager_script_path: /usr/local/bin/manage_lego_certs.sh

lego_acme_domains:
  - gitea.nixpi.de
  - files.nixpi.de
  - uptimekuma.nixpi.de
  - homeassistant.nixpi.de
  - vaultwarden.nixpi.de

######################################
### giftpilz0.server.haproxy

haproxy_config_maxconn: 500
haproxy_selinux_permissive: true

haproxy_config_http_apps:
  - name: gitea
    domain: gitea.nixpi.de
    force_https: true
    certificate: "{{ lego_cert_path }}/certificates/gitea.nixpi.de.pem"
    servers:
      - name: container
        host: 192.168.60.221
        port: 30002
  - name: pydio
    domain: files.nixpi.de
    force_https: true
    certificate: "{{ lego_cert_path }}/certificates/files.nixpi.de.pem"
    servers:
      - name: container
        host: 192.168.60.221
        port: 30024
  - name: vaultwarden
    domain: vaultwarden.nixpi.de
    force_https: true
    certificate: "{{ lego_cert_path }}/certificates/vaultwarden.nixpi.de.pem"
    servers:
      - name: container
        host: 192.168.60.221
        port: 30032
  - name: uptimekuma
    domain: uptimekuma.nixpi.de
    force_https: true
    certificate: "{{ lego_cert_path }}/certificates/uptimekuma.nixpi.de.pem"
    servers:
      - name: container
        host: 192.168.60.221
        port: 30031
  - name: homeassistant
    domain: homeassistant.nixpi.de
    force_https: true
    certificate: "{{ lego_cert_path }}/certificates/homeassistant.nixpi.de.pem"
    servers:
      - name: container
        host: 192.168.60.221
        port: 30007

haproxy_config_tcp_apps:
  - name: tcp-misc
    port: 30000-30050
    servers:
      - name: container
        host: 192.168.60.221
