---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: work
    source: 192.168.10.0/24
  - zone: cockpit
    source: 192.168.60.220

firewalld_rules_services:
  - service: ssh
    zone: work
    state: enabled
  - service: cockpit
    zone: work
    state: disabled
  - service: cockpit
    zone: cockpit
    state: enabled
  - service: ssh
    zone: cockpit
    state: enabled
  - service: ssh
    zone: cockpit
    state: enabled
  - service: http
    zone: work
    state: enabled
  - service: https
    zone: work
    state: enabled

firewalld_rules_ports:
  - port: 9100
    protocol: tcp
    zone: work
    state: enabled
  - port: 3100
    protocol: tcp
    zone: work
    state: enabled
