---
######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: work
    source: 192.168.178.0/24
  - zone: cockpit
    source: 192.168.178.220
  - zone: kubernetes
    source: 192.168.178.231
  - zone: kubernetes
    source: 192.168.178.232
  - zone: kubernetes
    source: 192.168.178.233
  - zone: container
    source: 192.168.178.221

firewalld_rules_services:
  - service: ssh
    zone: work
    state: enabled
  - service: cockpit
    zone: work
    state: disabled
  - service: cockpit
    zone: cockpit
    state: enabled
  - service: ssh
    zone: cockpit
    state: enabled
  - service: nfs
    zone: kubernetes
    state: enabled
  - service: nfs
    zone: container
    state: enabled

######################################
### giftpilz0.server.nfs

nfs_exports:
  - path: /srv/kubernetes/
    host: 192.168.178.0/24
    options: rw,sync,all_squash
    user: nobody
    group: nobody
    permissions: "750"
  - path: /srv/container/
    host: 192.168.178.0/24
    options: rw,sync,all_squash,security_label,anonuid=1000,anongid=1000
    user: nobody
    group: nobody
    permissions: "750"

nfs_firewalld_state: skip
