---
######################################
### giftpilz0.general.timezone

timezone_timezone: Europe/Berlin

######################################
### giftpilz0.general.cockpit

cockpit_firewalld_state: skip

######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: server
    source: 192.168.60.0/24
  - zone: loadbalancer
    source: 192.168.70.100
  - zone: loadbalancer
    source: 192.168.70.101
  - zone: loadbalancer
    source: 192.168.70.102

firewalld_rules_services:
  - service: cockpit
    zone: loadbalancer
    state: enabled
  - service: ssh
    zone: loadbalancer
    state: enabled

######################################
### giftpilz0.general.packages

packages_additional_package:
  - epel-release
  - mkpasswd
  - nfs-utils
  - nmap

packages_python_package: []
packages_rpmfusion_package_state: skip

packages_flatpak_repo_state: skip
packages_flatpak_package: []

######################################
### giftpilz0.general.monitoring

monitoring_agent_tag: 1.5.1
monitoring_agent_package_state: skip

monitoring_agent_config_remoteserver_loki: http://192.168.60.223:3100/loki/api/v1/push
monitoring_agent_config_remoteserver_prometheus: http://192.168.60.223:9100/api/v1/push
