---
######################################
### giftpilz0.general.timezone

timezone_timezone: Europe/Berlin

######################################
### giftpilz0.general.cockpit

cockpit_firewalld_state: skip

######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: work
    source: 192.168.10.0/24

firewalld_rules_services:
  - service: ssh
    zone: work
    state: enabled
  - service: cockpit
    zone: work
    state: disabled

######################################
### giftpilz0.general.packages

packages_additional_package:
  - epel-release
  - mkpasswd
  - nfs-utils
  - nmap

packages_python_package: []
packages_rpmfusion_package_state: skip

packages_flatpak_repo_state: skip
packages_flatpak_package: []
######################################
### giftpilz0.general.monitoring

monitoring_agent_tag: 1.3.1
monitoring_agent_package_state: present

monitoring_agent_config_remoteserver_loki: http://192.168.60.223:3100/loki/api/v1/push
monitoring_agent_config_remoteserver_prometheus: http://192.168.60.223:9100/api/v1/push
