---
podman_user: "container"

######################################
### giftpilz0.container.opencloud

# Proxy
opencloud_proxy_enabled: false
opencloud_proxy_http: ""
opencloud_proxy_https: ""
opencloud_proxy_no_proxy: ""

# Network
opencloud_network_enabled: true
opencloud_network_driver: "bridge"
opencloud_network_internal: false

# Network to join even when _network_enabled: false
opencloud_network_name: "opencloud-internal"

# Port mapping: host_port:container_port
opencloud_port_map_enabled: true
opencloud_port_map:
  - "127.0.0.1:9200:9200"

# Versions
# renovate: datasource=docker depName=opencloudeu/opencloud-rolling
opencloud_version: "7.1.0"

# Autoupdate
opencloud_autoupdate: true

# Environment
opencloud_domain: "https://opencloud.nixpi.de"
opencloud_log_level: "WARN"
opencloud_csp_oidc_origin: "https://login.nixpi.de"

opencloud_environment_vars:
  IDM_ADMIN_PASSWORD: "{{ opencloud_admin_password }}"
  OPEN_CLOUD_LOG_LEVEL: "{{ opencloud_log_level }}"
  OC_URL: "{{ opencloud_domain }}"
  OC_CORS_ALLOW_ORIGINS: "{{ opencloud_domain }}"
  PROXY_TLS: false
  PROXY_CSP_CONFIG_FILE_LOCATION: "/etc/opencloud/csp.yaml"
  FRONTEND_ARCHIVER_MAX_SIZE: 68719476736
  THUMBNAILS_MAX_CONCURRENT_REQUESTS: 64
  # External OIDC (Keycloak)
  OC_EXCLUDE_RUN_SERVICES: "idp"
  OC_OIDC_CLIENT_ID: "OpenCloudWeb"
  OC_OIDC_ISSUER: "https://login.nixpi.de/realms/nixpi"
  PROXY_AUTOPROVISION_ACCOUNTS: "true"
  PROXY_OIDC_REWRITE_WELLKNOWN: "true"
  PROXY_USER_CS3_CLAIM: "username"
  PROXY_USER_OIDC_CLAIM: "preferred_username"
  PROXY_ROLE_ASSIGNMENT_DRIVER: "oidc"
  GRAPH_ASSIGN_DEFAULT_USER_ROLE: "false"
  GRAPH_USERNAME_MATCH: "none"
  WEB_OPTION_ACCOUNT_EDIT_LINK_HREF: "https://login.nixpi.de/realms/nixpi/account"
  SETTINGS_SETUP_DEFAULT_ASSIGNMENTS: "false"

######################################
### giftpilz0.container.traefik

# Proxy
traefik_proxy_enabled: false
traefik_proxy_http: ""
traefik_proxy_https: ""
traefik_proxy_no_proxy: ""

# Version
# renovate: datasource=docker depName=traefik
traefik_version: "v3.7.1"

# Autoupdate
traefik_autoupdate: true

# ACME
traefik_acme_enabled: true
traefik_acme_ca_server: "https://acme-v02.api.letsencrypt.org/directory"
traefik_acme_challenge_type: dns
traefik_acme_dns_provider: "cloudflare"
traefik_acme_eab_enabled: false

# Logging
traefik_log_level: "INFO"

# Pasta TCP port forwarding into traefik container namespace
traefik_pasta_tcp_ports: "{{ opencloud_pasta_tcp_ports }}"

# Transport
traefik_transport_timeouts_enabled: true
traefik_transport_read_timeout: "12h"
traefik_transport_write_timeout: "12h"
traefik_transport_idle_timeout: "3m"

# HTTP services
traefik_http_services:
  - name: opencloud
    domain: opencloud.nixpi.de
    rule: "Host(`opencloud.nixpi.de`)"
    servers:
      - url: "http://127.0.0.1:9200"
    tls_enabled: true
    acme_enabled: true
    large_downloads: true
