opencloud_admin_password: ENC[AES256_GCM,data:Qg4StbBtCHROOWDvoZxk5+qBHlgJVQjtrSOzLQ==,iv:ULt3cJ9HXiB8oOk8jCkew+QkelAismxw3a6o14dIanc=,tag:vI8pSzG7KxExeU8clSgxKw==,type:str]
suwayomi_oidc_client_secret: ENC[AES256_GCM,data:74eZv6NwBg9uD64lkLei96TbC0+JtKlYvfoPTxc1k14sVwlVxAenLn9a+AbUAz0c,iv:tCJf7V+JkAv0GqTqGZSelQg8L9h11ve+Bn/e3KUDNQM=,tag:+Xh8lvsllbMoguGuQE2UQA==,type:str]
suwayomi_oidc_session_secret: ENC[AES256_GCM,data:DYhlADknwHfrqR4p+SMD1M7LjlBQp+m2dEYaJuQ4C8c=,iv:kuOhXX0ShH2PHYb1Od79okdiEEKQ3CG4ZIc7n1liVTo=,tag:RZepzMChX+MYTMtg4vf6EA==,type:str]
music_webui_oidc_client_secret: ENC[AES256_GCM,data:PRdP+6wLk0F4fvfZy7xLJvl6rUNdydkEqmiuLUWm+zuJVHMM8FJnEf0HspvQb+hg,iv:kQjigbqWIyGDpQEPsY46IK+z6U1L6rJLN/AVvecK0BI=,tag:pJCL3YVKzfhAWnww2DjVdw==,type:str]
music_webui_oidc_session_secret: ENC[AES256_GCM,data:Nd0XNmm9+LbFFdypfeL0SXlv2Q67XaTzx0oQMarl5cs=,iv:A5BA0xafYeKHFP6gBQXKLYkdrs8V37ieywulA8QYGYg=,tag:vVwgq3L73a3TvLvRnEMqLg==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:T3nCcc1GXmdXLerh6/9FB3WBioybCa6gMZA=,iv:5HzIpkZL58gvi7CtO1UOY7pe+svvRuDciSgh/aLYIb4=,tag:SoT/d/IQuK1FPL5l+yyhRg==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:nC1U1YM59o50LdU0Y370mn+c0mUH+yXUOMTqPU4SOpydS4ZFPObhhA==,iv:7Wul2/Jdo6CLyLNMrBFDq2bpA7nS+ExAghwEHvQMPQQ=,tag:yNwif92MKFF7n1J34JgIMg==,type:str]
sops:
    lastmodified: "2026-10-03T14:39:23Z"
    mac: ENC[AES256_GCM,data:NTwP/nm2AxHi+3T/J5DoDRKHOs7RqHi2KiRNcrAUGz4zjGtVrCL9qxFWTeSQpnxI3V0ta3nUuWRzlBhZGgIT1lBhc1yHziq5wwKlI6LFyI6fTLaaE9msFHl0WVsh5UnGpak+8Eg+0UpEFJD0qLO2qTABqjgBuGsAKHWXEb1mVis=,iv:x/YD61zYIwqQoTRcT76MnOMXYpb9wE4JCT5vdNNxm24=,tag:1g0C7x5lgqc8ZV74t7KxkQ==,type:str]
    pgp:
        - created_at: "2026-10-03T14:39:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAQCNoH853MKk8pItwbSCVuQ2SMsdUIvWGm1K9heXWSHow
            UU5DdckYJA6/f/pqrlBTuqymZ2iSJ0TlweO4xPJZUjgWQ2Q/qm1tWg53TVouApaR
            0l4BQla7B2Kn1/edoVbIpBDaVgTGaupR977snRwMuLMct84kieb7BcD/Mm5F39l/
            xBocsVNn4AQYDdmh8Y4jvTMwb2ksFTk+R/bjGIspfbVhOau5Z25W3fZ1Lf6cqyop
            =9kn+
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
