opencloud_admin_password: ENC[AES256_GCM,data:cDUA8EvY0yF4Ns3Rdl55d4OvNL8s/9z4jt5nuw==,iv:QpBiGW0YWOqhkFBypaLg9gBaFo+xHunVbuOAQtBtAlM=,tag:iY/Gs+O91zb938xJtHAe8g==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:EiosEMcPPZBD86/+nxSEoK+3f5vBXDjazho=,iv:/cLfG5ktYYChpgUumVAkOoeTQldwcBnHKLTKry/kcYY=,tag:C++8RkkO8C0IXvDKzs1b0Q==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:hzIC13Zk2lypbX2g9O4Yen2p9N8L649r8SdNYtNgMVcvnkulWeuzdQ==,iv:1W/e9bluqtDO9xBGib0AyHPNwF544rAmVoZ1llYLQ9c=,tag:BoclYCW7BgCNUxV2W3xIQg==,type:str]
sops:
    lastmodified: "2026-07-05T09:32:15Z"
    mac: ENC[AES256_GCM,data:YW1F/KfIGPl6q75t1APbhu0KLpSTMaqqnDOLEzfv9wtaNwDttCad97z8+mdy5z8S7iriDsZftAg3/USpGQViPzpn9rwgHKI2Mi1VanZuf5GJLOH3nlpEqpwVWiZDyQ2IeGZLyQEzwF8Vt9tLItvMj9irtiGqWx2td1f073MQsiY=,iv:us+/42jU3ahs54zQFxqcLVIO8i0xKkivuKtYq7d/en4=,tag:9Wotb/yPyIuMDu09IFsvFQ==,type:str]
    pgp:
        - created_at: "2026-07-05T09:32:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAnATi9qWMVfGWmvXebNawRA2WR1B6AvlOMWX0rsfPU3cw
            DhUI8o0JlbY2OkvRz97JnYchZ+9jL4YHjtfflzGg5EQbUXaxCqA78bi3D/n/lPmx
            0l4BbLzHVCtfL10uO/NqwhAp3z1VClN61VKVVBhrWcQ20qlSLJc8K7ougfQ3GbD0
            VUaVkwFQ0Sopz9RDEbq+9nYTd3T2RW2IrFSziRhw60hAwtgeJXNzQGKMMKkt9S8e
            =oIXQ
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
