opencloud_admin_password: ENC[AES256_GCM,data:8GMUS1M9Sz4u/9Iu8KQb9iuO/uZufYmuqs33ow==,iv:d87VS6dkC9x/6LPD1vuN/gECbiHrf6svUIKg58J00nU=,tag:TLqIOJ+0Pkq62OefPNWyPw==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:fBDUxmhfM3GyR8gIf5270O4bXtHqEJUMtOk=,iv:PIK9uhTx5rCeM822c8tV/b0sLPGr6afjl6YzRZwo8pg=,tag:6AfARh1DDbljrXAbZrao8g==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:h/On/908qLIf7hHMBjvgkln50O0KVPeHHxqiMtwHivNY7Q0KML4I8g==,iv:x0UwwGNeaaakdQG8XPyXaYBR7ybJHQFa8V31aKnJTg0=,tag:zrsyiWeCYTc4V/GEtaWm4Q==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:YdXYQpQjD4742MEtGWvJEURcZRjbdpjh202lrr3CTZF7GZcLjAR+HlAoWEjwZul5BpsxbWuNzNP2w6y6QcFw3WQE6Vx/0YGiGOi9jpMOwJDTtAw95y5VXbWOsjiYE/20u4tNJfrO+Zc5OEZ7cPzBfAWwwGB4uDmYfOg4fvCFpS4=,iv:jHO7CC8zreIpmx7XKmF/eE1rDmhErlxFYIy3VHTqRVY=,tag:711+OqfAIusRy6fHzCxJew==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAsSygmgnEa0iHWzcMNi0mEH+Ev117zW1iEC4nuAwyt30w
            TInbqEcftjqgIbNBQRYq+n8KEmocyi2D8U7R6IDukRzCUYv53a7F/tEk234lyDNg
            0l4BCKiEIARf1jDjf8Pi11Wl61OXlcdMR0d5ETIGzO8MDw6JVb36OzhwJOPFpprV
            jJMA0v4W8sToVaNlQG+drmkwrm1MnX4K8NK+O9cNeQqw7cu/JHNFkX7RHPma51Zs
            =QRry
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
