---
argument_specs:
  main:
    short_description: Install and enable Performance Co-Pilot for system performance monitoring.
    options:
      pcp_service_name:
        type: list
        elements: str
        required: false
        description: list of PCP systemd services to manage.

      pcp_service_state:
        type: str
        required: false
        choices:
          - reloaded
          - restarted
          - started
          - stopped
        description: desired state of PCP services.

      pcp_service_enabled:
        type: bool
        required: false
        description: whether PCP services are enabled at boot.

      pcp_package_state:
        type: str
        required: false
        choices:
          - present
          - absent
          - latest
        description: desired state of PCP packages.

      pcp_package:
        type: list
        elements: str
        required: false
        description: list of packages to install.
