# Settings
persistence true
persistence_location /mosquitto/data/
user mosquitto

allow_anonymous false
auth_plugin /usr/lib/go-auth.so
{% for option, value in mosquitto_go_auth_options.items() %}
auth_opt_{{ option }} {{ value if value is string else (value | join(',') if value is sequence else value) }}
{% endfor %}

listener 1883 0.0.0.0
protocol mqtt

listener 9001 0.0.0.0
protocol websockets
