# Settings
persistence true
persistence_location /mosquitto/data/

# Authentication
allow_anonymous false
password_file /mosquitto/config/passwd

# Listeners
listener 1883 0.0.0.0
protocol mqtt

listener 9001 0.0.0.0
protocol websockets
