# Settings
persistence true
persistence_location /mosquitto/data/

# Authentication
allow_anonymous false
password_file /mosquitto/config/passwd

# Listeners
listener {{ '1883 0.0.0.0' if not mosquitto_envoy_enabled else '1883 127.0.0.1' }}
protocol mqtt

listener {{ '9001 0.0.0.0' if not mosquitto_envoy_enabled else '9001 127.0.0.1' }}
protocol websockets
