monitoring_stack_mimir_access_key_id: ENC[AES256_GCM,data:UB5syov/zvZDLvykoR0A7XJWt1tndZXHl+k=,iv:QsBOBVtrI9gYDTM7cvkZF4SdGNVPtZt0YpKhEpvdQFA=,tag:6yQ6JkDCSTbGs/2+F3yn7A==,type:str]
monitoring_stack_mimir_secret_access_key: ENC[AES256_GCM,data:62bd2auWksZ3cuDR78mkM/kJCJHKpa0cT5wNCkmx6vQ029B+7IlxWSpYachjosUfKAjNKUVeuPiGeq9X4ZXK4A==,iv:ie+OeH1m9i/Yr0scQ4121PflehGZZcXCVXq45kSJiPU=,tag:MD6wxQufSa77s2GCsnIRaQ==,type:str]
monitoring_stack_loki_access_key_id: ENC[AES256_GCM,data:svYae4WsAvvrxZpMTRKBYnmVmfMQPrVuKdM=,iv:F3OJmgjBcjkqmAIm+8Fv0zT/GxlyysF9tqRkPnSm7Xg=,tag:Q0IGlHWaVgr2kHX18BuV3A==,type:str]
monitoring_stack_loki_secret_access_key: ENC[AES256_GCM,data:WB3wJNqVcG7ockEFVePCZUX23rroAMcaf8WZ6cLfMveLF6uY1f3DiJ7pt+Bg8FQOE67M+6I80NfVLybxiBvF3g==,iv:viCu9LbizIXYNIapIxm3V3Cvn9qp1ul4mTeFbF3WGjI=,tag:Tv8Zfs9iREoxvmaR8GLl/Q==,type:str]
monitoring_stack_garage_rpc_secret: ENC[AES256_GCM,data:l4xQwVObsBm8QkrXHt39bvvw7J6ymJJs/MzzaSk0UnL5zElOKAG53IYCRurqF1js8maGXEf21mHryhQ6+N+AfQ==,iv:96sABqdMZwE7XVJf8lOVxhMEU5RSXxsw0CkjlfbeHuE=,tag:793CscNsjw2oP8SUzOL01A==,type:str]
monitoring_stack_garage_admin_token: ENC[AES256_GCM,data:/RYxzem1khou58giyGtYf6QjSMnmnS6HEOpWKvZPqf25aUqAcYgaw3siXx0=,iv:5NngIt2Qv98uaUI4KlKggAkv298rPmIo6SLSl3wQ+tc=,tag:Jq3AzC4nVFAxwDuc2pyHUw==,type:str]
monitoring_stack_garage_metrics_token: ENC[AES256_GCM,data:WluM/EGDRBWmIJkIoJcAtVkDllsD4bkRfM1SevYRRa5K128Nt6IeXqne1So=,iv:euPtuXhUZl+SOFdEaqQkX7xqMShCpcFjOuI5njeAcbA=,tag:Zagu22wCStsbIYc0O47gNg==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:f+efMBGOEyZ0DZsHvJfqOmLdk7YrPhT9m0Y=,iv:i2cRVMfsIkzi7Ris1LpsonfeHqr6M/Ujk91X07lHzwc=,tag:6Cy3gN3O2oMAreRDucb1Sw==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:c7NFWc63s1aTNhquk97/urqnY3K7CbKOhAtNJgOZJWAGpYab4jco2Q==,iv:iXHAL47Xe/D6wHXhQ/YwOiYFQLZcGas60oODP7vuljk=,tag:zI6zZ6U5rY4qQD0oior70A==,type:str]
sops:
    lastmodified: "2026-08-02T13:27:10Z"
    mac: ENC[AES256_GCM,data:6DMgOLnQZwFD7YyEaffIrDUboCOkcNexiqAOdT+od/ghZ20PD98aTPXW8oygCpCJ79bkVYMC7uisBoN1wtodA7w5gaj3HfU7qwbjUMcw5ow7POGTO3ywFJrc2pN8uVt6eIy5705MnA39Y77XXy8tfHxXUc4HTEPd2/VZ/vHChhw=,iv:ndiR5zGdxgt0b3vRRxC1mJ2WPaUiSuwEvmccYKH5Rr4=,tag:XPOroxvdHXD33khvl06UgQ==,type:str]
    pgp:
        - created_at: "2026-08-02T13:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAOnk7ceufXsHxg5i1buh9eBpIIJUPilr1bYvt4QPW+lAw
            nOh9TE4KOmTZRtjtBL7bVexl1hLJcoo/RKcAYRFC+Sbpmb7CPub2UVhDMVsmCCZi
            0l4BkT53g5I18n3DLAwSNWJDlzPZhqaBdqhFdWApeQux7iFwocdUUaJBoGrPmZ6w
            yOUgfdd1BsXecbeZ7Tml2ts78Dp1cTN8J4Yr7qh3H0Dbqogezsl19q1XYBgxrRJx
            =7gH0
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
