monitoring_stack_mimir_access_key_id: ENC[AES256_GCM,data:OAZ/bi822wQOc9KDp4RtMpJdthvSwQO+//k=,iv:2qpsepC0oiGAW2Yldq1PSo8GENc4mgK7V/5Rk0wlB2E=,tag:ksceJzVPQN2wCoNsZ/KQ7w==,type:str]
monitoring_stack_mimir_secret_access_key: ENC[AES256_GCM,data:caIh6vJaGxljxYqqHaoXSw+INg36yyf15BmSlpOODxfaNI0e6bwk+TnI7UWcKbjWkB3CN5tnJWkeu5MrF1RzSg==,iv:skq/kiy5MDvButHIGRFpqYYtEKxESPzAMT/ZcDpuQXk=,tag:xaRoiBTN1sXvpdKOkjHFpw==,type:str]
monitoring_stack_loki_access_key_id: ENC[AES256_GCM,data:FS798vAYcDDayE5KAvALEH0IqL7+cZdil24=,iv:a055OvjK82+ZJLQnNzHQ7T4uX1kK+GcZ/aYXMY70sCY=,tag:plSlhJymGUYMs9pLEC8s/Q==,type:str]
monitoring_stack_loki_secret_access_key: ENC[AES256_GCM,data:Dqy9kB/iH+WOZ6QcgypAYTodkfo+eS8Kxivr+eKfl5oephNrphDxwIsgChKefWM3nXeOziTvvlWl8GZAbqCwLA==,iv:t/LjdWGHPNQdaNqH4kGvJXRA9A9f7PVxNTs0gd88byg=,tag:js0p6qepDguwxnFWl4E8Cg==,type:str]
monitoring_stack_garage_rpc_secret: ENC[AES256_GCM,data:yoDwKEUoFcepBFJ8qSbDn6dTYqvRPTkAqJquAKjwqb6gFiL1/jWqxlz+1bjVklbkZm3Ntg/zLwgqVEQqwz5pRA==,iv:w1wYP1J9Boy4WbNgyjlMaUGhCUXJMP8+2Fk0CozosVI=,tag:gg9Pah5FHR8sDprtuT2itg==,type:str]
monitoring_stack_garage_admin_token: ENC[AES256_GCM,data:mzBvZ3qGfw8I5FJzC5O9V0AQaRfb6O8WylybhsflKVzifg84IrOAbjrVz6o=,iv:nuDMn63NM8UBNsDs9K0hyEwSiWg6WaB4Z5/hohF1Ylo=,tag:Lk/IZ79Iv9n3FvPsq0Tmtg==,type:str]
monitoring_stack_garage_metrics_token: ENC[AES256_GCM,data:JF3BF9+fpZzwa1C7fZc99KFwcIAbB0ElqCTzDzZdpir/BooJScwd8apH6T4=,iv:exP16O1d2OaeFn1925/8+YqmWmKzZnaU0PgGcliDp3g=,tag:YDfL7ftzhABMSGNE0UaDag==,type:str]
traefik_acme_email: ENC[AES256_GCM,data:pTnXamzX/Ccvb7BqpaLloTf8Iu5OGZ8NjI4=,iv:VFFYkM+8yqFNqNGW8Jbx6hFau+csjcYqg82bjgz9rrE=,tag:bOTI4HMeaYLux+z2e2Qk/A==,type:str]
traefik_environment_vars:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:nNEnixoG9R2tzcthaI0XSUyQh0lUhqqEXf9maAEikFNNQGCab0Cq9Q==,iv:q887nZbjItU1H6Q/FbiC+KE2eN6iFzcZP98oXgtbUKI=,tag:YuiWpC/8vx/s6jal7x6gUA==,type:str]
sops:
    lastmodified: "2026-07-25T11:57:04Z"
    mac: ENC[AES256_GCM,data:dcgCJsiK6ajWQz9TxF7M+YauXlT7WqhY2s4IAWf1cDtJW4fOrBEwLw5XTNu/DsNVC65KCcwan47jmwwPMNSoYw5uDxt1ahU3Tv+9isepjwvcVxXF49UlHkWjs853nBUcoskuDy6xFoDyI0QRSU9/r8N3e8HaGAR2lybrrEV/8ss=,iv:NjnDZVd1pjHAgXkg9HtWVb17dghyFDGAVKuz4ldw9GE=,tag:3YQQggfMjfIX5ILF7wO+Qw==,type:str]
    pgp:
        - created_at: "2026-07-25T11:57:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlsbw3CUfQvcSAQdAogrvFbCkgnMQQHxIAUsQRp6z1eI6U5gFuqH+oBq2qm4w
            liHe0R2e9sNjPOqabK3Fg4d3v/2FzUWnPsB14r7nUnYR49edGdy4aphbl+gvcx/e
            0lwBE8YN5DOqIIR6KRb9L+nZWyTFsJTKpbgsvaAPlYO+7z7y9P/Ws78WyCq2Axa9
            WC7U3rq3GGgiBS3dHsKPDlZPn5qRy7qFrVy1aImflGaA2IoXx3XB6rgMYhfViA==
            =T3Zp
            -----END PGP MESSAGE-----
          fp: E610D1262E9505511041BE8A3E5CDE3393570604
    unencrypted_suffix: _unencrypted
    version: 3.13.0
